version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: "UTC"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:15"
      timezone: "UTC"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: "UTC"
    ignore:
      - dependency-name: "eslint"
        update-types:
          - "version-update:semver-major"
    groups:
      javascript-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:45"
      timezone: "UTC"
    groups:
      root-docker-images:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/apps/web"
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: "UTC"
    groups:
      web-docker-images:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: "/rust"
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: "UTC"
    groups:
      rust-dependencies:
        patterns:
          - "*"
