"""Configuration for grounded knowledge retrieval."""

from koda.config import STATE_ROOT_DIR, _env
from koda.memory.config import MEMORY_EMBEDDING_MODEL

KNOWLEDGE_ENABLED: bool = _env("KNOWLEDGE_ENABLED", "true").lower() == "true"
KNOWLEDGE_EMBEDDING_MODEL: str = _env("KNOWLEDGE_EMBEDDING_MODEL", MEMORY_EMBEDDING_MODEL)
KNOWLEDGE_MAX_RESULTS: int = int(_env("KNOWLEDGE_MAX_RESULTS", "6"))
KNOWLEDGE_RECALL_THRESHOLD: float = float(_env("KNOWLEDGE_RECALL_THRESHOLD", "0.35"))
KNOWLEDGE_CONTEXT_MAX_TOKENS: int = int(_env("KNOWLEDGE_CONTEXT_MAX_TOKENS", "2200"))
KNOWLEDGE_RECALL_TIMEOUT: float = float(_env("KNOWLEDGE_RECALL_TIMEOUT", "2.0"))
KNOWLEDGE_MAX_CHARS_PER_CHUNK: int = int(_env("KNOWLEDGE_MAX_CHARS_PER_CHUNK", "900"))
KNOWLEDGE_MAX_OBSERVED_PATTERNS: int = int(_env("KNOWLEDGE_MAX_OBSERVED_PATTERNS", "3"))
KNOWLEDGE_CANDIDATE_MIN_CONFIDENCE: float = float(_env("KNOWLEDGE_CANDIDATE_MIN_CONFIDENCE", "0.75"))
KNOWLEDGE_CANDIDATE_SUCCESS_THRESHOLD: int = int(_env("KNOWLEDGE_CANDIDATE_SUCCESS_THRESHOLD", "3"))
KNOWLEDGE_CANDIDATE_FAILURE_THRESHOLD: int = int(_env("KNOWLEDGE_CANDIDATE_FAILURE_THRESHOLD", "2"))
KNOWLEDGE_SOURCE_GLOBS: list[str] = [
    part.strip()
    for part in _env(
        "KNOWLEDGE_SOURCE_GLOBS",
        "README.md,AGENTS.md,docs/ai/*.md",
    ).split(",")
    if part.strip()
]
KNOWLEDGE_WORKSPACE_SOURCE_GLOBS: list[str] = [
    part.strip()
    for part in _env(
        "KNOWLEDGE_WORKSPACE_SOURCE_GLOBS",
        "README.md,AGENTS.md,docs/*.md,docs/**/*.md",
    ).split(",")
    if part.strip()
]
KNOWLEDGE_WORKSPACE_MAX_FILES: int = int(_env("KNOWLEDGE_WORKSPACE_MAX_FILES", "24"))
KNOWLEDGE_ALLOWED_LAYERS: list[str] = [
    part.strip().lower()
    for part in _env(
        "KNOWLEDGE_ALLOWED_LAYERS",
        "canonical_policy,approved_runbook,workspace_doc,observed_pattern",
    ).split(",")
    if part.strip()
]
KNOWLEDGE_MAX_SOURCE_AGE_DAYS: int = int(_env("KNOWLEDGE_MAX_SOURCE_AGE_DAYS", "3650"))
KNOWLEDGE_REQUIRE_OWNER_PROVENANCE: bool = _env("KNOWLEDGE_REQUIRE_OWNER_PROVENANCE", "false").lower() == "true"
KNOWLEDGE_REQUIRE_FRESHNESS_PROVENANCE: bool = _env("KNOWLEDGE_REQUIRE_FRESHNESS_PROVENANCE", "false").lower() == "true"
KNOWLEDGE_PROMOTION_MODE: str = _env("KNOWLEDGE_PROMOTION_MODE", "review_queue").strip().lower()
KNOWLEDGE_STRATEGY_DEFAULT: str = _env("KNOWLEDGE_STRATEGY_DEFAULT", "langgraph_current").strip().lower()
KNOWLEDGE_TRACE_SAMPLING_RATE: float = float(_env("KNOWLEDGE_TRACE_SAMPLING_RATE", "1.0"))
KNOWLEDGE_GRAPH_ENABLED: bool = _env("KNOWLEDGE_GRAPH_ENABLED", "true").lower() == "true"
KNOWLEDGE_MULTIMODAL_GRAPH_ENABLED: bool = _env("KNOWLEDGE_MULTIMODAL_GRAPH_ENABLED", "true").lower() == "true"
KNOWLEDGE_EVALUATION_SAMPLING_RATE: float = float(_env("KNOWLEDGE_EVALUATION_SAMPLING_RATE", "1.0"))
KNOWLEDGE_CITATION_POLICY: str = _env("KNOWLEDGE_CITATION_POLICY", "operational_required").strip().lower()
KNOWLEDGE_V2_ENABLED: bool = _env("KNOWLEDGE_V2_ENABLED", "true").lower() == "true"
KNOWLEDGE_V2_MAX_GRAPH_HOPS: int = int(_env("KNOWLEDGE_V2_MAX_GRAPH_HOPS", "3"))
KNOWLEDGE_V2_CROSS_ENCODER_MODEL: str = _env("KNOWLEDGE_V2_CROSS_ENCODER_MODEL", "").strip()
KNOWLEDGE_V2_STORAGE_MODE: str = _env("KNOWLEDGE_V2_STORAGE_MODE", "primary").strip().lower()
KNOWLEDGE_V2_OBJECT_STORE_ROOT: str = _env("KNOWLEDGE_V2_OBJECT_STORE_ROOT", str(STATE_ROOT_DIR / "knowledge_v2"))
KNOWLEDGE_V2_POSTGRES_DSN: str = _env("KNOWLEDGE_V2_POSTGRES_DSN", "").strip()
KNOWLEDGE_V2_POSTGRES_SCHEMA: str = _env("KNOWLEDGE_V2_POSTGRES_SCHEMA", "knowledge_v2").strip()
KNOWLEDGE_V2_POSTGRES_POOL_MIN_SIZE: int = int(_env("KNOWLEDGE_V2_POSTGRES_POOL_MIN_SIZE", "1"))
KNOWLEDGE_V2_POSTGRES_POOL_MAX_SIZE: int = int(_env("KNOWLEDGE_V2_POSTGRES_POOL_MAX_SIZE", "6"))
KNOWLEDGE_V2_POSTGRES_START_RETRIES: int = int(_env("KNOWLEDGE_V2_POSTGRES_START_RETRIES", "2"))
KNOWLEDGE_V2_POSTGRES_RETRY_BASE_SECONDS: float = float(_env("KNOWLEDGE_V2_POSTGRES_RETRY_BASE_SECONDS", "0.5"))
KNOWLEDGE_V2_EMBEDDING_DIMENSION: int = int(_env("KNOWLEDGE_V2_EMBEDDING_DIMENSION", "1024"))
KNOWLEDGE_V2_NEO4J_URI: str = _env("KNOWLEDGE_V2_NEO4J_URI", "").strip()
KNOWLEDGE_V2_NEO4J_USER: str = _env("KNOWLEDGE_V2_NEO4J_USER", "").strip()
KNOWLEDGE_V2_NEO4J_PASSWORD: str = _env("KNOWLEDGE_V2_NEO4J_PASSWORD", "").strip()
KNOWLEDGE_V2_S3_BUCKET: str = _env("KNOWLEDGE_V2_S3_BUCKET", "").strip()
KNOWLEDGE_V2_S3_PREFIX: str = _env("KNOWLEDGE_V2_S3_PREFIX", "knowledge-v2").strip()
KNOWLEDGE_V2_S3_ENDPOINT_URL: str = _env("KNOWLEDGE_V2_S3_ENDPOINT_URL", "").strip()
KNOWLEDGE_V2_S3_REGION: str = _env("KNOWLEDGE_V2_S3_REGION", "").strip()
KNOWLEDGE_V2_S3_ACCESS_KEY_ID: str = _env("KNOWLEDGE_V2_S3_ACCESS_KEY_ID", "").strip()
KNOWLEDGE_V2_S3_SECRET_ACCESS_KEY: str = _env("KNOWLEDGE_V2_S3_SECRET_ACCESS_KEY", "").strip()
KNOWLEDGE_V2_OTEL_ENABLED: bool = _env("KNOWLEDGE_V2_OTEL_ENABLED", "true").lower() == "true"
KNOWLEDGE_V2_INGEST_WORKER_ENABLED: bool = _env("KNOWLEDGE_V2_INGEST_WORKER_ENABLED", "true").lower() == "true"
KNOWLEDGE_V2_INGEST_POLL_SECONDS: float = float(_env("KNOWLEDGE_V2_INGEST_POLL_SECONDS", "5.0"))
KNOWLEDGE_V2_INGEST_LEASE_SECONDS: int = int(_env("KNOWLEDGE_V2_INGEST_LEASE_SECONDS", "60"))
KNOWLEDGE_V2_INGEST_BATCH_LIMIT: int = int(_env("KNOWLEDGE_V2_INGEST_BATCH_LIMIT", "8"))
KNOWLEDGE_V2_INGEST_MAX_QUEUE_DEPTH: int = int(_env("KNOWLEDGE_V2_INGEST_MAX_QUEUE_DEPTH", "128"))
KNOWLEDGE_V2_INGEST_MAX_POISONED_JOBS: int = int(_env("KNOWLEDGE_V2_INGEST_MAX_POISONED_JOBS", "0"))
KNOWLEDGE_SEMANTIC_JUDGE_ENABLED: bool = _env("KNOWLEDGE_SEMANTIC_JUDGE_ENABLED", "true").lower() == "true"
KNOWLEDGE_SEMANTIC_JUDGE_SUPPORT_THRESHOLD: float = float(_env("KNOWLEDGE_SEMANTIC_JUDGE_SUPPORT_THRESHOLD", "0.6"))
KNOWLEDGE_ALLOWED_SOURCE_LABELS: list[str] = [
    part.strip() for part in _env("KNOWLEDGE_ALLOWED_SOURCE_LABELS", "").split(",") if part.strip()
]
KNOWLEDGE_ALLOWED_WORKSPACE_ROOTS: list[str] = [
    part.strip() for part in _env("KNOWLEDGE_ALLOWED_WORKSPACE_ROOTS", "").split(",") if part.strip()
]
