import type { McpCapabilityRisk } from "@/lib/contracts/mcp-risk";
import type { RunGraphSnapshot, RunReplayPlan } from "@/lib/contracts/run-graph";
import type { SandboxDoctorResult } from "@/lib/contracts/sandbox-doctor";

export const phase2RunReplayFixture: RunReplayPlan = {
  replay_version: "run_replay.v1",
  run_id: "run_42",
  task_id: 42,
  availability: "available",
  mode: "offline",
  provider_calls_disabled: true,
  redaction_applied: true,
  generated_at: "2026-05-16T14:10:00.000Z",
  missing_dependencies: [],
  steps: [
    {
      node_id: "node_queue",
      type: "queue_wait",
      label: "Queue wait",
      status: "completed",
      deterministic: true,
      redacted: false,
    },
    {
      node_id: "node_policy",
      type: "policy_gate",
      label: "Sandbox policy gate",
      status: "completed",
      deterministic: true,
      redacted: false,
    },
    {
      node_id: "node_tool",
      type: "tool_call",
      label: "Run shell command",
      status: "completed",
      deterministic: true,
      redacted: true,
      notes: "Command args were redacted before replay export.",
    },
  ],
};

export const phase2RunGraphFixture: RunGraphSnapshot = {
  run_graph_version: "run_graph.v1",
  run_id: "run_42",
  root_node_id: "node_queue",
  agent_id: "ATLAS",
  task_id: 42,
  status: "completed",
  started_at: "2026-05-16T14:00:00.000Z",
  completed_at: "2026-05-16T14:10:00.000Z",
  summary: "Task completed with policy, tool, artifact, and cost nodes.",
  redactions: { count: 2, fields: ["env.API_KEY", "tool.args.secret"] },
  replay: phase2RunReplayFixture,
  nodes: [
    {
      id: "node_queue",
      type: "queue_wait",
      label: "Queue wait",
      status: "completed",
      severity: "info",
      agent_id: "ATLAS",
      task_id: 42,
      attempt: 1,
      started_at: "2026-05-16T14:00:00.000Z",
      completed_at: "2026-05-16T14:00:08.000Z",
      duration_ms: 8000,
      summary: "Task accepted and picked up by a runtime worker.",
    },
    {
      id: "node_model",
      parent_id: "node_queue",
      type: "model_call",
      label: "Model call",
      status: "completed",
      severity: "info",
      agent_id: "ATLAS",
      task_id: 42,
      attempt: 1,
      duration_ms: 1600,
      summary: "Planner selected a guarded shell action.",
    },
    {
      id: "node_policy",
      parent_id: "node_model",
      type: "policy_gate",
      label: "Policy gate",
      status: "completed",
      severity: "info",
      agent_id: "ATLAS",
      task_id: 42,
      attempt: 1,
      summary: "Write action allowed after approval requirement was met.",
    },
    {
      id: "node_tool",
      parent_id: "node_policy",
      type: "tool_call",
      label: "Shell tool",
      status: "completed",
      severity: "info",
      agent_id: "ATLAS",
      task_id: 42,
      attempt: 1,
      duration_ms: 420,
      redactions: { count: 1, fields: ["tool.args.secret"] },
      summary: "Tool output captured for offline replay.",
    },
    {
      id: "node_artifact",
      parent_id: "node_tool",
      type: "artifact",
      label: "Patch artifact",
      status: "completed",
      severity: "info",
      agent_id: "ATLAS",
      task_id: 42,
      attempt: 1,
      artifact_refs: ["artifact_patch_1"],
      summary: "Patch artifact stored with provenance.",
    },
  ],
};

export const phase2DoctorFixture: SandboxDoctorResult = {
  doctor_version: "sandbox_doctor.v1",
  status: "degraded",
  generated_at: "2026-05-16T14:09:00.000Z",
  agent_id: "ATLAS",
  task_id: 42,
  degraded_components: ["browser"],
  effective_policy: {
    policy_version: "sandbox_policy.v1",
    agent_id: "ATLAS",
    task_id: 42,
    runtime_state: "degraded",
    scopes: ["filesystem", "network", "shell", "browser", "mount"],
    read_only: false,
    network_mode: "restricted",
    shell_mode: "guarded",
    browser_mode: "unavailable",
    ttl_seconds: 3600,
  },
  checks: [
    {
      id: "fs_mounts",
      scope: "mount",
      title: "Mount allowlist",
      severity: "info",
      status: "passed",
      message: "Workspace mount is inside the runtime root.",
      user_action: "No action required.",
      run_graph_node_id: "node_policy",
    },
    {
      id: "browser_unavailable",
      scope: "browser",
      title: "Browser runtime",
      severity: "warning",
      status: "degraded",
      message: "Browser attach is unavailable for this run.",
      user_action: "Reconnect the browser runtime before browser actions.",
    },
  ],
};

export const phase2McpRiskFixture: McpCapabilityRisk = {
  taxonomy_version: "mcp_risk.v1",
  capability_kind: "tool",
  capability_name: "delete_project",
  risk_class: "destructive_write",
  risk_tags: ["keyword_destructive", "keyword_network_write"],
  approval_default: "require_approval",
  grant_state: "requires_approval",
  redaction_required: true,
  policy_source: "tool_registry",
  rationale: "The tool can delete remote project state.",
  warning: "Requires operator approval before execution.",
};
