#!/usr/bin/env python3
"""Sync the npm package README from the repository root README."""

from __future__ import annotations

import argparse
import re
import sys
import tarfile
from pathlib import Path

from release_metadata import REPOSITORY_URL

ROOT = Path(__file__).resolve().parents[1]
SOURCE_README_PATH = ROOT / "README.md"
PACKAGE_README_PATH = ROOT / "packages" / "cli" / "README.md"

GENERATED_HEADER = (
    "<!-- Generated from ../../README.md by scripts/sync_npm_readme.py. Do not edit this file directly. -->\n\n"
)
MARKDOWN_LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")
MARKDOWN_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")
HTML_ATTR_RE = re.compile(r'(?P<attr>href|src)="(?P<target>[^"]+)"')
NPM_README_GITHUB_REF = "main"


def _split_target(target: str) -> tuple[str, str]:
    if "#" not in target:
        return target, ""
    path, anchor = target.split("#", 1)
    return path, f"#{anchor}"


def _is_external(target: str) -> bool:
    return (
        "://" in target
        or target.startswith("mailto:")
        or target.startswith("#")
        or target.startswith("data:")
        or target.startswith("tel:")
    )


def _normalize_local_target(target: str, *, image: bool) -> str:
    if _is_external(target):
        return target

    path_part, anchor = _split_target(target)
    source = (SOURCE_README_PATH.parent / path_part).resolve()
    try:
        relative = source.relative_to(ROOT).as_posix()
    except ValueError as exc:  # pragma: no cover - defensive
        raise RuntimeError(f"README reference escapes repository: {target}") from exc

    if image:
        return f"https://raw.githubusercontent.com/OpenKodaAI/koda/{NPM_README_GITHUB_REF}/{relative}"

    base = "tree" if source.is_dir() else "blob"
    return f"{REPOSITORY_URL}/{base}/{NPM_README_GITHUB_REF}/{relative}{anchor}"


def build_package_readme() -> str:
    text = SOURCE_README_PATH.read_text(encoding="utf-8")
    text = text.replace("http://127.0.0.1:", "http://localhost:")

    def replace_markdown_image(match: re.Match[str]) -> str:
        alt, target = match.groups()
        return f"![{alt}]({_normalize_local_target(target, image=True)})"

    def replace_markdown_link(match: re.Match[str]) -> str:
        label, target = match.groups()
        return f"[{label}]({_normalize_local_target(target, image=False)})"

    def replace_html_attr(match: re.Match[str]) -> str:
        attr = match.group("attr")
        target = match.group("target")
        normalized = _normalize_local_target(target, image=attr == "src")
        return f'{attr}="{normalized}"'

    rendered = MARKDOWN_IMAGE_RE.sub(replace_markdown_image, text)
    rendered = MARKDOWN_LINK_RE.sub(replace_markdown_link, rendered)
    rendered = HTML_ATTR_RE.sub(replace_html_attr, rendered)
    return GENERATED_HEADER + rendered.strip() + "\n"


def sync_npm_readme(*, write: bool) -> bool:
    expected = build_package_readme()
    actual = PACKAGE_README_PATH.read_text(encoding="utf-8") if PACKAGE_README_PATH.exists() else None
    drift = actual != expected
    if write and drift:
        PACKAGE_README_PATH.write_text(expected, encoding="utf-8")
    return drift


def package_tarball_readme_matches(tarball_path: Path) -> bool:
    expected = build_package_readme()
    if not tarball_path.exists():
        raise RuntimeError(f"{tarball_path} does not exist")

    with tarfile.open(tarball_path, "r:gz") as tarball:
        member = tarball.extractfile("package/README.md")
        if member is None:
            raise RuntimeError(f"{tarball_path} does not contain package/README.md")
        actual = member.read().decode("utf-8")
    return actual == expected


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Rewrite the package README in place.")
    parser.add_argument(
        "--package-tarball",
        type=Path,
        default=None,
        help="Validate package/README.md inside an npm .tgz against the generated README.",
    )
    return parser


def main() -> int:
    parser = _build_parser()
    args = parser.parse_args()
    if args.write and args.package_tarball is not None:
        parser.error("--write cannot be combined with --package-tarball")

    if args.package_tarball is not None:
        try:
            matches = package_tarball_readme_matches(args.package_tarball)
        except (RuntimeError, tarfile.TarError, UnicodeDecodeError) as exc:
            print(str(exc), file=sys.stderr)
            return 1
        if matches:
            return 0
        print(
            f"npm package README drift detected inside {args.package_tarball}.",
            file=sys.stderr,
        )
        return 1

    drift = sync_npm_readme(write=args.write)
    if drift and not args.write:
        print(
            "npm package README drift detected. Run `python3 scripts/sync_npm_readme.py --write`.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
