#!/usr/bin/env python3
"""Sync the npm package README from the repository root README."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from release_metadata import REPOSITORY_URL, load_project_version

ROOT = Path(__file__).resolve().parents[1]
SOURCE_README_PATH = ROOT / "README.md"
PACKAGE_README_PATH = ROOT / "packages" / "cli" / "README.md"

GENERATED_HEADER = (
    "<!-- Generated from ../../README.md by scripts/sync_npm_readme.py. Do not edit this file directly. -->\n\n"
)
MARKDOWN_LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")
MARKDOWN_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")
HTML_ATTR_RE = re.compile(r'(?P<attr>href|src)="(?P<target>[^"]+)"')


def _split_target(target: str) -> tuple[str, str]:
    if "#" not in target:
        return target, ""
    path, anchor = target.split("#", 1)
    return path, f"#{anchor}"


def _is_external(target: str) -> bool:
    return (
        "://" in target
        or target.startswith("mailto:")
        or target.startswith("#")
        or target.startswith("data:")
        or target.startswith("tel:")
    )


def _normalize_local_target(target: str, *, image: bool, version: str) -> str:
    if _is_external(target):
        return target

    path_part, anchor = _split_target(target)
    source = (SOURCE_README_PATH.parent / path_part).resolve()
    try:
        relative = source.relative_to(ROOT).as_posix()
    except ValueError as exc:  # pragma: no cover - defensive
        raise RuntimeError(f"README reference escapes repository: {target}") from exc

    if image:
        return f"https://raw.githubusercontent.com/OpenKodaAI/koda/v{version}/{relative}"

    base = "tree" if source.is_dir() else "blob"
    return f"{REPOSITORY_URL}/{base}/v{version}/{relative}{anchor}"


def build_package_readme() -> str:
    version = load_project_version()
    text = SOURCE_README_PATH.read_text(encoding="utf-8")
    text = text.replace("http://127.0.0.1:", "http://localhost:")

    def replace_markdown_image(match: re.Match[str]) -> str:
        alt, target = match.groups()
        return f"![{alt}]({_normalize_local_target(target, image=True, version=version)})"

    def replace_markdown_link(match: re.Match[str]) -> str:
        label, target = match.groups()
        return f"[{label}]({_normalize_local_target(target, image=False, version=version)})"

    def replace_html_attr(match: re.Match[str]) -> str:
        attr = match.group("attr")
        target = match.group("target")
        normalized = _normalize_local_target(target, image=attr == "src", version=version)
        return f'{attr}="{normalized}"'

    rendered = MARKDOWN_IMAGE_RE.sub(replace_markdown_image, text)
    rendered = MARKDOWN_LINK_RE.sub(replace_markdown_link, rendered)
    rendered = HTML_ATTR_RE.sub(replace_html_attr, rendered)
    return GENERATED_HEADER + rendered.strip() + "\n"


def sync_npm_readme(*, write: bool) -> bool:
    expected = build_package_readme()
    actual = PACKAGE_README_PATH.read_text(encoding="utf-8") if PACKAGE_README_PATH.exists() else None
    drift = actual != expected
    if write and drift:
        PACKAGE_README_PATH.write_text(expected, encoding="utf-8")
    return drift


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Rewrite the package README in place.")
    return parser


def main() -> int:
    args = _build_parser().parse_args()
    drift = sync_npm_readme(write=args.write)
    if drift and not args.write:
        print(
            "npm package README drift detected. Run `python3 scripts/sync_npm_readme.py --write`.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
