"""Authoritative MCP catalog entries used by the control plane."""

from __future__ import annotations

from typing import Any


def _env_field(
    key: str,
    label: str,
    *,
    required: bool,
    input_type: str = "password",
) -> dict[str, Any]:
    return {
        "key": key,
        "label": label,
        "required": required,
        "input_type": input_type,
    }


AUTHORITATIVE_MCP_CATALOG: tuple[dict[str, Any], ...] = (
    {
        "server_key": "supabase",
        "display_name": "Supabase",
        "description": "Supabase MCP remoto oficial com escopo por projeto e modo somente leitura por padrao.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.supabase.com/mcp",
        "url": "https://mcp.supabase.com/mcp",
        "env_schema": (
            _env_field("SUPABASE_ACCESS_TOKEN", "Personal Access Token", required=False),
            _env_field("SUPABASE_PROJECT_REF", "Project Reference", required=False, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://supabase.com/docs/guides/getting-started/mcp",
        "logo_key": "supabase",
        "category": "cloud",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official_manual_limited",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": (
            "Use OAuth remoto por padrao. Fallback por PAT so para CI/headless. Koda impone read_only=true por default."
        ),
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Banco, auth e edge functions",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {SUPABASE_ACCESS_TOKEN}",
            },
            "fixed_url_params": {"read_only": "true"},
            "url_params": [{"name": "project_ref", "env_key": "SUPABASE_PROJECT_REF"}],
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "stripe",
        "display_name": "Stripe",
        "description": "Stripe MCP remoto oficial com OAuth remoto por agente.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.stripe.com",
        "url": "https://mcp.stripe.com",
        "env_schema": (_env_field("STRIPE_SECRET_KEY", "Restricted API Key", required=False),),
        "headers_schema": (),
        "documentation_url": "https://docs.stripe.com/mcp",
        "logo_key": "stripe",
        "category": "data",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth remoto por padrao; restricted key apenas para automacao/headless.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Pagamentos, assinaturas e faturamento",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {STRIPE_SECRET_KEY}",
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "excalidraw",
        "display_name": "Excalidraw",
        "description": "Servidor community/manual para diagramas no Excalidraw.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "excalidraw-mcp"),
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://github.com/excalidraw/excalidraw-mcp",
        "logo_key": "excalidraw",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "no_auth",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual integration; do not promise official support.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Diagramas e whiteboarding colaborativo",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "vercel",
        "display_name": "Vercel",
        "description": "Vercel MCP remoto oficial com discovery real de tools.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.vercel.com",
        "url": "https://mcp.vercel.com",
        "env_schema": (_env_field("VERCEL_TOKEN", "Vercel API Token", required=False),),
        "headers_schema": (),
        "documentation_url": "https://vercel.com/docs/agent-resources/vercel-mcp",
        "logo_key": "vercel",
        "category": "development",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth remoto por padrao; token manual apenas para automacao/headless quando necessario.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Deploy, logs e preview deployments",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {VERCEL_TOKEN}",
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "granola",
        "display_name": "Granola",
        "description": "Servidor community/manual para notas e transcricoes de reunioes.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "granola-mcp-server"),
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://github.com/btn0s/granola-mcp",
        "logo_key": "granola",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "local_session",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual integration; depends on the provider's local flow.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Meeting notes e transcricoes",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "sentry",
        "display_name": "Sentry",
        "description": "Servidor community/manual para erros, traces e projetos do Sentry.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@sentry/mcp-server@0.31.0"),
        "env_schema": (
            _env_field("SENTRY_ACCESS_TOKEN", "Auth Token", required=True),
            _env_field("SENTRY_HOST", "Self-hosted URL", required=False, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://docs.sentry.io/product/sentry-mcp/",
        "logo_key": "sentry",
        "category": "development",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Manter como community/manual ate haver caminho oficial consolidado de MCP remoto/OAuth.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Monitoramento de erros e stack traces",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "linear",
        "display_name": "Linear",
        "description": "Linear MCP remoto oficial com OAuth 2.1 + DCR.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.linear.app/mcp",
        "url": "https://mcp.linear.app/mcp",
        "env_schema": (_env_field("LINEAR_API_KEY", "Personal API Key", required=False),),
        "headers_schema": (),
        "documentation_url": "https://linear.app/docs/mcp",
        "logo_key": "linear",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": (
            "OAuth remoto por padrao; Authorization Bearer tambem pode ser usado com API key ou OAuth token existente."
        ),
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Gestao de projetos e issues",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {LINEAR_API_KEY}",
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "brave_search",
        "display_name": "Brave Search",
        "description": "Busca web provider-guided com API key.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@modelcontextprotocol/server-brave-search"),
        "env_schema": (_env_field("BRAVE_API_KEY", "Brave Search API Key", required=True),),
        "headers_schema": (),
        "documentation_url": "https://brave.com/search/api/",
        "logo_key": "brave",
        "category": "data",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "provider_guided_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Usar API key; nao tratar como OAuth.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Busca web com privacidade",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "slack",
        "display_name": "Slack",
        "description": "Slack MCP remoto oficial com app de identidade fixa e OAuth confidencial.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.slack.com/mcp",
        "url": "https://mcp.slack.com/mcp",
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://docs.slack.dev/ai/slack-mcp-server/",
        "logo_key": "slack",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_confidential",
        "official_support_level": "official",
        "oauth_mode": "confidential",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Requer app Slack com identidade fixa e credenciais gerenciadas pela instalacao.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Mensageria e automacoes de workspace",
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "confidential",
                "supports_manual": False,
            },
        },
    },
    {
        "server_key": "notion",
        "display_name": "Notion",
        "description": "Notion MCP remoto oficial por workspace/agente.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.notion.com/mcp",
        "url": "https://mcp.notion.com/mcp",
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://developers.notion.com/guides/mcp/get-started-with-mcp",
        "logo_key": "notion",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Conectar via OAuth remoto do MCP oficial por workspace.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Wiki, docs e bases de dados",
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": False,
            },
        },
    },
    {
        "server_key": "cloudflare",
        "display_name": "Cloudflare",
        "description": "Cloudflare API MCP remoto oficial com OAuth e fallback por API token para CI.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.cloudflare.com/mcp",
        "url": "https://mcp.cloudflare.com/mcp",
        "env_schema": (_env_field("CLOUDFLARE_API_TOKEN", "Cloudflare API Token", required=False),),
        "headers_schema": (),
        "documentation_url": "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/",
        "logo_key": "cloudflare",
        "category": "cloud",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth remoto por padrao. API token manual apenas para CI/headless.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Cloudflare API remoto oficial",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {CLOUDFLARE_API_TOKEN}",
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "google_maps",
        "display_name": "Google Maps",
        "description": "Toolkit oficial focado em documentacao e code assist do Google Maps Platform.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@googlemaps/code-assist-mcp@latest"),
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://developers.google.com/maps/ai/mcp",
        "logo_key": "google_maps",
        "category": "development",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "no_auth",
        "official_support_level": "official_manual_limited",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Nao modelar como conexao de conta do usuario; foco em docs e exemplos oficiais.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Toolkit oficial de docs e samples",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "todoist",
        "display_name": "Todoist",
        "description": "Community/manual integration with a Todoist API token.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "todoist-mcp-server"),
        "env_schema": (_env_field("TODOIST_API_TOKEN", "Todoist API Token", required=True),),
        "headers_schema": (),
        "documentation_url": "https://developer.todoist.com/",
        "logo_key": "todoist",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Manual/third-party integration.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Tarefas e produtividade pessoal",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "obsidian",
        "display_name": "Obsidian",
        "description": "Community/manual integration for local Obsidian vaults.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@mauricio.wolff/mcp-obsidian", "/path/to/vault"),
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://www.npmjs.com/package/@mauricio.wolff/mcp-obsidian",
        "logo_key": "obsidian",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "local_session",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Local integration; requires manual vault configuration.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Vault local e conhecimento pessoal",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "mongodb",
        "display_name": "MongoDB",
        "description": "Servidor oficial/manual para MongoDB com connection string ou credenciais Atlas.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "mongodb-mcp-server"),
        "env_schema": (
            _env_field("MDB_MCP_CONNECTION_STRING", "MongoDB Connection String", required=True),
            _env_field("MDB_MCP_READ_ONLY", "Read Only", required=False, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://www.mongodb.com/docs/mcp-server/",
        "logo_key": "mongodb",
        "category": "data",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "connection_string",
        "official_support_level": "official_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Usar connection string ou credenciais Atlas; nao inventar OAuth.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Banco de documentos e Atlas",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "hubspot",
        "display_name": "HubSpot",
        "description": "HubSpot Remote MCP oficial/beta com apps MCP auth autogerenciados.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.hubspot.com",
        "url": "https://mcp.hubspot.com",
        "env_schema": (_env_field("PRIVATE_APP_ACCESS_TOKEN", "Private App Token", required=False),),
        "headers_schema": (),
        "documentation_url": "https://developers.hubspot.com/mcp",
        "logo_key": "hubspot",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_confidential",
        "official_support_level": "official_beta",
        "oauth_mode": "confidential",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Remote MCP em beta; apps MCP auth gerenciados na HubSpot Developer Platform.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "CRM, contatos e pipeline",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {PRIVATE_APP_ACCESS_TOKEN}",
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "confidential",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "figma",
        "display_name": "Figma",
        "description": "Figma MCP oficial com suporte remoto e opcao de sessao local via desktop.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.figma.com/mcp",
        "url": "https://mcp.figma.com/mcp",
        "env_schema": (_env_field("FIGMA_API_KEY", "Personal Access Token", required=False),),
        "headers_schema": (),
        "documentation_url": "https://help.figma.com/hc/en-us/articles/32132100833559-Guide-to-the-Figma-MCP-server",
        "logo_key": "figma",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_confidential",
        "official_support_level": "official",
        "oauth_mode": "confidential",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Preferir remoto oficial; manter possibilidade de fallback local/desktop em fases posteriores.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Design, arquivos e Dev Mode",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {FIGMA_API_KEY}",
            },
            "local_fallback": {
                "transport_type": "stdio",
                "command": ["npx", "-y", "figma-developer-mcp", "--stdio"],
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "confidential",
                "supports_manual": True,
                "supports_local_fallback": True,
            },
        },
    },
    {
        "server_key": "twilio",
        "display_name": "Twilio",
        "description": "Community/manual integration with Account SID and Auth Token.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@twilio-alpha/mcp"),
        "env_schema": (
            _env_field("TWILIO_ACCOUNT_SID", "Account SID", required=True, input_type="text"),
            _env_field("TWILIO_AUTH_TOKEN", "Auth Token", required=True),
        ),
        "headers_schema": (),
        "documentation_url": "https://github.com/twilio-labs/mcp",
        "logo_key": "twilio",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Manter como community/manual ate existir caminho oficial consolidado.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "SMS, voz e automacoes de comunicacao",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "postgres_mcp",
        "display_name": "PostgreSQL (MCP)",
        "description": "Servidor community/manual para PostgreSQL via connection string.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@henkey/postgres-mcp-server"),
        "env_schema": (_env_field("DATABASE_URL", "Database URL", required=True),),
        "headers_schema": (),
        "documentation_url": "https://www.npmjs.com/package/@henkey/postgres-mcp-server",
        "logo_key": "postgresql",
        "category": "data",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "connection_string",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual integration.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Banco relacional por connection string",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
)


def authoritative_mcp_catalog_entries() -> list[dict[str, Any]]:
    """Return authoritative MCP catalog entries as mutable payloads."""
    return [dict(entry) for entry in AUTHORITATIVE_MCP_CATALOG]
