"""Authoritative MCP catalog entries used by the control plane."""

from __future__ import annotations

from typing import Any


def _env_field(
    key: str,
    label: str,
    *,
    required: bool,
    input_type: str = "password",
) -> dict[str, Any]:
    return {
        "key": key,
        "label": label,
        "required": required,
        "input_type": input_type,
    }


AUTHORITATIVE_MCP_CATALOG: tuple[dict[str, Any], ...] = (
    {
        "server_key": "supabase",
        "display_name": "Supabase",
        "description": "Supabase MCP remoto oficial com escopo por projeto e modo somente leitura por padrao.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.supabase.com/mcp",
        "url": "https://mcp.supabase.com/mcp",
        "env_schema": (
            _env_field("SUPABASE_ACCESS_TOKEN", "Personal Access Token", required=False),
            _env_field("SUPABASE_PROJECT_REF", "Project Reference", required=False, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://supabase.com/docs/guides/getting-started/mcp",
        "logo_key": "supabase",
        "category": "cloud",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official_manual_limited",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": (
            "Use OAuth remoto por padrao. Fallback por PAT so para CI/headless. Koda impone read_only=true por default."
        ),
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Banco, auth e edge functions",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {SUPABASE_ACCESS_TOKEN}",
            },
            "fixed_url_params": {"read_only": "true"},
            "url_params": [{"name": "project_ref", "env_key": "SUPABASE_PROJECT_REF"}],
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "stripe",
        "display_name": "Stripe",
        "description": "Stripe MCP remoto oficial com OAuth remoto por agente.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.stripe.com",
        "url": "https://mcp.stripe.com",
        "env_schema": (_env_field("STRIPE_SECRET_KEY", "Restricted API Key", required=False),),
        "headers_schema": (),
        "documentation_url": "https://docs.stripe.com/mcp",
        "logo_key": "stripe",
        "category": "data",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth remoto por padrao; restricted key apenas para automacao/headless.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Pagamentos, assinaturas e faturamento",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {STRIPE_SECRET_KEY}",
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "excalidraw",
        "display_name": "Excalidraw",
        "description": "Servidor community/manual para diagramas no Excalidraw.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "excalidraw-mcp"),
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://github.com/excalidraw/excalidraw-mcp",
        "logo_key": "excalidraw",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "no_auth",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual integration; do not promise official support.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Diagramas e whiteboarding colaborativo",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "vercel",
        "display_name": "Vercel",
        "description": "Vercel MCP remoto oficial com discovery real de tools.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.vercel.com",
        "url": "https://mcp.vercel.com",
        "env_schema": (_env_field("VERCEL_TOKEN", "Vercel API Token", required=False),),
        "headers_schema": (),
        "documentation_url": "https://vercel.com/docs/agent-resources/vercel-mcp",
        "logo_key": "vercel",
        "category": "development",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth remoto por padrao; token manual apenas para automacao/headless quando necessario.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Deploy, logs e preview deployments",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {VERCEL_TOKEN}",
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "granola",
        "display_name": "Granola",
        "description": "Servidor community/manual para notas e transcricoes de reunioes.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "granola-mcp-server"),
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://github.com/btn0s/granola-mcp",
        "logo_key": "granola",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "local_session",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual integration; depends on the provider's local flow.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Meeting notes e transcricoes",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "sentry",
        "display_name": "Sentry",
        "description": "Servidor community/manual para erros, traces e projetos do Sentry.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@sentry/mcp-server@0.31.0"),
        "env_schema": (
            _env_field("SENTRY_ACCESS_TOKEN", "Auth Token", required=True),
            _env_field("SENTRY_HOST", "Self-hosted URL", required=False, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://docs.sentry.io/product/sentry-mcp/",
        "logo_key": "sentry",
        "category": "development",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Manter como community/manual ate haver caminho oficial consolidado de MCP remoto/OAuth.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Monitoramento de erros e stack traces",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "linear",
        "display_name": "Linear",
        "description": "Linear MCP remoto oficial com OAuth 2.1 + DCR.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.linear.app/mcp",
        "url": "https://mcp.linear.app/mcp",
        "env_schema": (_env_field("LINEAR_API_KEY", "Personal API Key", required=False),),
        "headers_schema": (),
        "documentation_url": "https://linear.app/docs/mcp",
        "logo_key": "linear",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": (
            "OAuth remoto por padrao; Authorization Bearer tambem pode ser usado com API key ou OAuth token existente."
        ),
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Gestao de projetos e issues",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {LINEAR_API_KEY}",
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "brave_search",
        "display_name": "Brave Search",
        "description": "Busca web provider-guided com API key.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@modelcontextprotocol/server-brave-search"),
        "env_schema": (_env_field("BRAVE_API_KEY", "Brave Search API Key", required=True),),
        "headers_schema": (),
        "documentation_url": "https://brave.com/search/api/",
        "logo_key": "brave",
        "category": "data",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "provider_guided_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Usar API key; nao tratar como OAuth.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Busca web com privacidade",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "slack",
        "display_name": "Slack",
        "description": "Slack MCP remoto oficial com app de identidade fixa e OAuth confidencial.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.slack.com/mcp",
        "url": "https://mcp.slack.com/mcp",
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://docs.slack.dev/ai/slack-mcp-server/",
        "logo_key": "slack",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_confidential",
        "official_support_level": "official",
        "oauth_mode": "confidential",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Requer app Slack com identidade fixa e credenciais gerenciadas pela instalacao.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Mensageria e automacoes de workspace",
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "confidential",
                "supports_manual": False,
            },
        },
    },
    {
        "server_key": "notion",
        "display_name": "Notion",
        "description": "Notion MCP remoto oficial por workspace/agente.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.notion.com/mcp",
        "url": "https://mcp.notion.com/mcp",
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://developers.notion.com/guides/mcp/get-started-with-mcp",
        "logo_key": "notion",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Conectar via OAuth remoto do MCP oficial por workspace.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Wiki, docs e bases de dados",
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": False,
            },
        },
    },
    {
        "server_key": "cloudflare",
        "display_name": "Cloudflare",
        "description": "Cloudflare API MCP remoto oficial com OAuth e fallback por API token para CI.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.cloudflare.com/mcp",
        "url": "https://mcp.cloudflare.com/mcp",
        "env_schema": (_env_field("CLOUDFLARE_API_TOKEN", "Cloudflare API Token", required=False),),
        "headers_schema": (),
        "documentation_url": "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/",
        "logo_key": "cloudflare",
        "category": "cloud",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth remoto por padrao. API token manual apenas para CI/headless.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Cloudflare API remoto oficial",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {CLOUDFLARE_API_TOKEN}",
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "google_maps",
        "display_name": "Google Maps",
        "description": "Toolkit oficial focado em documentacao e code assist do Google Maps Platform.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@googlemaps/code-assist-mcp@latest"),
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://developers.google.com/maps/ai/mcp",
        "logo_key": "google_maps",
        "category": "development",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "no_auth",
        "official_support_level": "official_manual_limited",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Nao modelar como conexao de conta do usuario; foco em docs e exemplos oficiais.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Toolkit oficial de docs e samples",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "todoist",
        "display_name": "Todoist",
        "description": "Community/manual integration with a Todoist API token.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "todoist-mcp-server"),
        "env_schema": (_env_field("TODOIST_API_TOKEN", "Todoist API Token", required=True),),
        "headers_schema": (),
        "documentation_url": "https://developer.todoist.com/",
        "logo_key": "todoist",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Manual/third-party integration.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Tarefas e produtividade pessoal",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "obsidian",
        "display_name": "Obsidian",
        "description": "Community/manual integration for local Obsidian vaults.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@mauricio.wolff/mcp-obsidian", "/path/to/vault"),
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://www.npmjs.com/package/@mauricio.wolff/mcp-obsidian",
        "logo_key": "obsidian",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "local_session",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Local integration; requires manual vault configuration.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Vault local e conhecimento pessoal",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "mongodb",
        "display_name": "MongoDB",
        "description": "Servidor oficial/manual para MongoDB com connection string ou credenciais Atlas.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "mongodb-mcp-server"),
        "env_schema": (
            _env_field("MDB_MCP_CONNECTION_STRING", "MongoDB Connection String", required=True),
            _env_field("MDB_MCP_READ_ONLY", "Read Only", required=False, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://www.mongodb.com/docs/mcp-server/",
        "logo_key": "mongodb",
        "category": "data",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "connection_string",
        "official_support_level": "official_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Usar connection string ou credenciais Atlas; nao inventar OAuth.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Banco de documentos e Atlas",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "hubspot",
        "display_name": "HubSpot",
        "description": "HubSpot Remote MCP oficial/beta com apps MCP auth autogerenciados.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.hubspot.com",
        "url": "https://mcp.hubspot.com",
        "env_schema": (_env_field("PRIVATE_APP_ACCESS_TOKEN", "Private App Token", required=False),),
        "headers_schema": (),
        "documentation_url": "https://developers.hubspot.com/mcp",
        "logo_key": "hubspot",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_confidential",
        "official_support_level": "official_beta",
        "oauth_mode": "confidential",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Remote MCP em beta; apps MCP auth gerenciados na HubSpot Developer Platform.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "CRM, contatos e pipeline",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {PRIVATE_APP_ACCESS_TOKEN}",
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "confidential",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "figma",
        "display_name": "Figma",
        "description": "Figma MCP oficial com suporte remoto e opcao de sessao local via desktop.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.figma.com/mcp",
        "url": "https://mcp.figma.com/mcp",
        "env_schema": (_env_field("FIGMA_API_KEY", "Personal Access Token", required=False),),
        "headers_schema": (),
        "documentation_url": "https://help.figma.com/hc/en-us/articles/32132100833559-Guide-to-the-Figma-MCP-server",
        "logo_key": "figma",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_confidential",
        "official_support_level": "official",
        "oauth_mode": "confidential",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Preferir remoto oficial; manter possibilidade de fallback local/desktop em fases posteriores.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Design, arquivos e Dev Mode",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {FIGMA_API_KEY}",
            },
            "local_fallback": {
                "transport_type": "stdio",
                "command": ["npx", "-y", "figma-developer-mcp", "--stdio"],
            },
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "confidential",
                "supports_manual": True,
                "supports_local_fallback": True,
            },
        },
    },
    {
        "server_key": "twilio",
        "display_name": "Twilio",
        "description": "Community/manual integration with Account SID and Auth Token.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@twilio-alpha/mcp"),
        "env_schema": (
            _env_field("TWILIO_ACCOUNT_SID", "Account SID", required=True, input_type="text"),
            _env_field("TWILIO_AUTH_TOKEN", "Auth Token", required=True),
        ),
        "headers_schema": (),
        "documentation_url": "https://github.com/twilio-labs/mcp",
        "logo_key": "twilio",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Manter como community/manual ate existir caminho oficial consolidado.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "SMS, voz e automacoes de comunicacao",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "postgres_mcp",
        "display_name": "PostgreSQL",
        "description": "Servidor community/manual para PostgreSQL via connection string.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@henkey/postgres-mcp-server"),
        "env_schema": (_env_field("DATABASE_URL", "Database URL", required=True),),
        "headers_schema": (),
        "documentation_url": "https://www.npmjs.com/package/@henkey/postgres-mcp-server",
        "logo_key": "postgresql",
        "category": "data",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "connection_string",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual integration.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Banco relacional por connection string",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "atlassian",
        "display_name": "Atlassian",
        "description": "Atlassian Rovo MCP remoto oficial com OAuth 2.1 + DCR. Suporta Jira issues e Confluence pages.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.atlassian.com/v1/mcp",
        "url": "https://mcp.atlassian.com/v1/mcp",
        "env_schema": (
            _env_field("ATLASSIAN_SITE_URL", "Site URL (apenas para API token)", required=False, input_type="text"),
            _env_field("ATLASSIAN_EMAIL", "Email (apenas para API token)", required=False, input_type="text"),
            _env_field("ATLASSIAN_API_TOKEN", "API Token (fallback)", required=False),
        ),
        "headers_schema": (),
        "documentation_url": "https://support.atlassian.com/atlassian-rovo-mcp-server/",
        "logo_key": "atlassian",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth remoto por padrao via Rovo MCP server. API token apenas para automacao headless.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Jira + Confluence em um servidor",
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "github_mcp",
        "display_name": "GitHub",
        "description": "GitHub MCP Server oficial via api.githubcopilot.com/mcp com OAuth.",
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://api.githubcopilot.com/mcp",
        "url": "https://api.githubcopilot.com/mcp",
        "env_schema": (_env_field("GITHUB_PERSONAL_ACCESS_TOKEN", "Personal Access Token (fallback)", required=False),),
        "headers_schema": (),
        "documentation_url": "https://github.com/github/github-mcp-server",
        "logo_key": "github",
        "category": "development",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth via GitHub. PAT apenas para CI/headless.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Repos, issues, PRs e Actions",
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "gitlab_mcp",
        "display_name": "GitLab",
        "description": "Servidor community/manual para GitLab via Personal Access Token.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@modelcontextprotocol/server-gitlab"),
        "env_schema": (
            _env_field("GITLAB_PERSONAL_ACCESS_TOKEN", "Personal Access Token", required=True),
            _env_field(
                "GITLAB_API_URL",
                "API URL (self-hosted)",
                required=False,
                input_type="text",
            ),
        ),
        "headers_schema": (),
        "documentation_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab",
        "logo_key": "gitlab",
        "category": "development",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual integration. OAuth ainda nao consolidado para MCP GitLab.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Repositorios, MRs e pipelines",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "bitbucket",
        "display_name": "Bitbucket",
        "description": (
            "Servidor community/manual para Bitbucket Cloud e Server. "
            "Usa Username + App Password (Cloud) ou HTTP Access Token (Server)."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@nexus2520/bitbucket-mcp-server"),
        "env_schema": (
            _env_field("BITBUCKET_USERNAME", "Username (Cloud)", required=False, input_type="text"),
            _env_field("BITBUCKET_APP_PASSWORD", "App Password (Cloud)", required=False),
            _env_field("BITBUCKET_TOKEN", "HTTP Access Token (Server)", required=False),
            _env_field("BITBUCKET_URL", "Base URL (self-hosted)", required=False, input_type="text"),
            _env_field("BITBUCKET_DEFAULT_WORKSPACE", "Workspace padrao (Cloud)", required=False, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://www.npmjs.com/package/@nexus2520/bitbucket-mcp-server",
        "logo_key": "bitbucket",
        "category": "development",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": (
            "Community/manual. Para Cloud, gere uma App Password em "
            "id.atlassian.com/manage-profile/security/app-passwords. Para Server, "
            "use HTTP access token."
        ),
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Repositorios, PRs e pipelines",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "gmail",
        "display_name": "Gmail",
        "description": "Servidor MCP para Gmail via OAuth do Google (autoauth).",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@gongrzhe/server-gmail-autoauth-mcp"),
        "env_schema": (
            _env_field("GMAIL_OAUTH_CLIENT_ID", "OAuth Client ID (fallback)", required=False),
            _env_field("GMAIL_OAUTH_CLIENT_SECRET", "OAuth Client Secret (fallback)", required=False),
        ),
        "headers_schema": (),
        "documentation_url": "https://developers.google.com/gmail/api",
        "logo_key": "gmail",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "community_manual",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth via Google. Credenciais opcionais apenas para deployments self-hosted.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Email, threads, labels",
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "google_calendar",
        "display_name": "Google Calendar",
        "description": "Servidor MCP para Google Calendar com OAuth.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@cocal/google-calendar-mcp"),
        "env_schema": (
            _env_field("GOOGLE_OAUTH_CLIENT_ID", "OAuth Client ID (fallback)", required=False),
            _env_field("GOOGLE_OAUTH_CLIENT_SECRET", "OAuth Client Secret (fallback)", required=False),
        ),
        "headers_schema": (),
        "documentation_url": "https://developers.google.com/calendar/api",
        "logo_key": "google_calendar",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "community_manual",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth via Google. Credenciais opcionais apenas para deployments self-hosted.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Eventos, calendarios, agendamentos",
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "google_drive",
        "display_name": "Google Drive",
        "description": "Servidor MCP para Google Drive com OAuth.",
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@modelcontextprotocol/server-gdrive"),
        "env_schema": (
            _env_field("GDRIVE_OAUTH_CLIENT_ID", "OAuth Client ID (fallback)", required=False),
            _env_field("GDRIVE_OAUTH_CLIENT_SECRET", "OAuth Client Secret (fallback)", required=False),
        ),
        "headers_schema": (),
        "documentation_url": "https://developers.google.com/drive/api",
        "logo_key": "google_drive",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "community_manual",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth via Google. Credenciais opcionais apenas para deployments self-hosted.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Arquivos, pastas, busca",
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "aws_knowledge",
        "display_name": "AWS Knowledge",
        "description": (
            "Servidor MCP oficial da AWS com acesso publico (sem credenciais) "
            "a documentacao, blogs, What's New e Well-Architected."
        ),
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://knowledge-mcp.global.api.aws",
        "url": "https://knowledge-mcp.global.api.aws",
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://docs.aws.amazon.com/mcp/",
        "logo_key": "aws",
        "category": "cloud",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "no_auth",
        "official_support_level": "official",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Servidor publico read-only. Sem credenciais necessarias.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Documentacao AWS e best practices",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": False,
            },
        },
    },
    # ------------------------------------------------------------ Wave 3 (10/2026)
    {
        "server_key": "microsoft_365",
        "display_name": "Microsoft 365",
        "description": (
            "Servidor MCP comunitario (Lokka) que conecta ao Microsoft Graph. "
            "Cobre Outlook, Teams e OneDrive. OAuth 2.1 do Microsoft Identity Platform."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@merill/lokka@0.3.0"),
        "env_schema": (
            _env_field("TENANT_ID", "Tenant ID (fallback)", required=False, input_type="text"),
            _env_field("CLIENT_ID", "Client ID (fallback)", required=False, input_type="text"),
            _env_field("CLIENT_SECRET", "Client Secret (fallback)", required=False),
        ),
        "headers_schema": (),
        "documentation_url": "https://github.com/merill/lokka",
        "logo_key": "microsoft_365",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "community_manual",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual integration via Lokka. OAuth via Microsoft.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Outlook, Teams, OneDrive via Microsoft Graph",
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "firecrawl",
        "display_name": "Firecrawl",
        "description": (
            "Servidor MCP oficial da Firecrawl: scrape, crawl, busca web e extracao "
            "estruturada via LLM. Auth via API Key."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "firecrawl-mcp@3.14.1"),
        "env_schema": (_env_field("FIRECRAWL_API_KEY", "API Key", required=True),),
        "headers_schema": (),
        "documentation_url": "https://docs.firecrawl.dev/mcp",
        "logo_key": "firecrawl",
        "category": "general",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "official",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Servidor oficial. Single-key auth.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Web scraping e crawling para pesquisa",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "posthog",
        "display_name": "PostHog",
        "description": (
            "Servidor MCP remoto oficial em mcp.posthog.com. Eventos, funnels, "
            "dashboards, feature flags e personas. Auth via Personal API Key."
        ),
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.posthog.com/mcp",
        "url": "https://mcp.posthog.com/mcp",
        "env_schema": (
            _env_field("POSTHOG_API_KEY", "Personal API Key", required=True),
            _env_field("POSTHOG_HOST", "Host (self-hosted)", required=False, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://posthog.com/docs/model-context-protocol",
        "logo_key": "posthog",
        "category": "data",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "official",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Servidor remoto oficial. Token via Authorization: Bearer.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Product analytics, eventos e feature flags",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {POSTHOG_API_KEY}",
            },
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "discord",
        "display_name": "Discord",
        "description": (
            "Servidor MCP comunitario para Discord. Mensagens, threads, membros, "
            "moderacao. Auth via Bot Token (Discord Developer Portal)."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "discord-mcp@2.4.0"),
        "env_schema": (_env_field("DISCORD_BOT_TOKEN", "Bot Token", required=True),),
        "headers_schema": (),
        "documentation_url": "https://www.npmjs.com/package/discord-mcp",
        "logo_key": "discord",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual. Crie bot em discord.com/developers/applications.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Mensagens, canais, threads e moderacao",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "grafana",
        "display_name": "Grafana",
        "description": (
            "Servidor MCP oficial da Grafana Labs (Python via uvx). Dashboards, "
            "queries Prometheus/Loki, alertas. Auth via Service Account Token."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("uvx", "mcp-grafana==0.13.1"),
        "env_schema": (
            _env_field("GRAFANA_URL", "Grafana URL", required=True, input_type="text"),
            _env_field("GRAFANA_API_KEY", "Service Account Token", required=True),
        ),
        "headers_schema": (),
        "documentation_url": "https://github.com/grafana/mcp-grafana",
        "logo_key": "grafana",
        "category": "cloud",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "official",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Requer uv (uvx) instalado. Service account token estavel.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Dashboards, alertas e queries Prometheus/Loki",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "canva",
        "display_name": "Canva",
        "description": (
            "Servidor MCP remoto oficial em mcp.canva.com via OAuth. Designs, brand templates, exports e assets."
        ),
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.canva.com/mcp",
        "url": "https://mcp.canva.com/mcp",
        "env_schema": (),
        "headers_schema": (),
        "documentation_url": "https://www.canva.dev/docs/connect/mcp/",
        "logo_key": "canva",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "official",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "OAuth-only via Canva Connect. Sem fallback manual.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Designs, brand templates e exports",
            "oauth_runtime_auth": {"type": "authorization_bearer"},
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": False,
            },
        },
    },
    {
        "server_key": "box",
        "display_name": "Box",
        "description": (
            "Servidor MCP comunitario para Box Cloud. Files, folders, sharing. "
            "OAuth 2.0 do Box (preferencial) ou Developer Token."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "box-mcp-server@0.3.1"),
        "env_schema": (_env_field("BOX_DEVELOPER_TOKEN", "Developer Token (fallback)", required=False),),
        "headers_schema": (),
        "documentation_url": "https://www.npmjs.com/package/box-mcp-server",
        "logo_key": "box",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": True,
        "auth_strategy": "oauth_dcr",
        "official_support_level": "community_manual",
        "oauth_mode": "dcr",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual. OAuth via Box (preferencial); developer token apenas para dev local.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Storage corporativo, files e sharing",
            "auth_capabilities": {
                "oauth_enabled": True,
                "oauth_mode": "dcr",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "n8n",
        "display_name": "n8n",
        "description": (
            "Servidor MCP comunitario para n8n (cloud ou self-hosted). Workflows, "
            "executions, credentials metadata. Auth via API Key."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "n8n-mcp@2.50.0"),
        "env_schema": (
            _env_field("N8N_API_KEY", "n8n API Key", required=True),
            _env_field("N8N_BASE_URL", "Base URL", required=True, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://www.npmjs.com/package/n8n-mcp",
        "logo_key": "n8n",
        "category": "general",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual. Suporta cloud e self-hosted via N8N_BASE_URL.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Workflow automation, executions e credentials",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "aws_api",
        "display_name": "AWS API",
        "description": (
            "Servidor MCP oficial AWS Labs (Python via uvx) para execucao real "
            "de operacoes AWS via API. S3, EC2, Lambda, IAM, CloudWatch, DynamoDB. "
            "Default always_ask em todas as tools; operador pode habilitar read_only_mode."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("uvx", "awslabs.aws-api-mcp-server==1.3.33"),
        "env_schema": (
            _env_field("AWS_ACCESS_KEY_ID", "Access Key ID", required=True),
            _env_field("AWS_SECRET_ACCESS_KEY", "Secret Access Key", required=True),
            _env_field("AWS_REGION", "Default Region", required=True, input_type="text"),
            _env_field("AWS_SESSION_TOKEN", "Session Token (temporary)", required=False),
            _env_field("AWS_PROFILE", "AWS Profile (~/.aws/credentials)", required=False, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://github.com/awslabs/mcp/tree/main/src/aws-api-mcp-server",
        "logo_key": "aws",
        "category": "cloud",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "official",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": (
            "Servidor oficial AWS Labs. Requer uv (uvx) instalado. "
            "Tools destructive nativas: setar always_ask em todas e usar read_only_mode."
        ),
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Execucao real de tools AWS (S3, EC2, Lambda, IAM)",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    # ------------------------------------------------------------ Wave 4 (10/2026)
    {
        "server_key": "postman",
        "display_name": "Postman",
        "description": (
            "Servidor MCP para Postman API: workspaces, collections, requests, "
            "environments, mock servers. Auth via API Key."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "postman-mcp-server@1.2.0"),
        "env_schema": (_env_field("POSTMAN_API_KEY", "API Key", required=True),),
        "headers_schema": (),
        "documentation_url": "https://www.npmjs.com/package/postman-mcp-server",
        "logo_key": "postman",
        "category": "development",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Servidor community alinhado com a Postman API. Single-key auth.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Workspaces, collections e mock servers",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "zapier",
        "display_name": "Zapier",
        "description": (
            "Servidor MCP remoto oficial Zapier: 6.000+ apps via Zaps. URL "
            "personalizada por usuario com token embutido."
        ),
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://mcp.zapier.com/api/mcp/sse",
        "url": "https://mcp.zapier.com/api/mcp/sse",
        "env_schema": (_env_field("ZAPIER_MCP_URL", "MCP URL (with embedded token)", required=True),),
        "headers_schema": (),
        "documentation_url": "https://zapier.com/mcp",
        "logo_key": "zapier",
        "category": "general",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "official",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": ("Servidor remoto oficial. Token embutido na URL personalizada gerada em mcp.zapier.com."),
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "6.000+ apps via Zaps automatizados",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "netlify",
        "display_name": "Netlify",
        "description": (
            "Servidor MCP oficial Netlify. Sites, deploys, env vars, edge "
            "functions, formularios e dominios. Auth via Personal Access Token."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "@netlify/mcp@1.15.1"),
        "env_schema": (_env_field("NETLIFY_PERSONAL_ACCESS_TOKEN", "Personal Access Token", required=True),),
        "headers_schema": (),
        "documentation_url": "https://docs.netlify.com/welcome/build-with-ai/netlify-mcp-server/",
        "logo_key": "netlify",
        "category": "development",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "official",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Servidor oficial Netlify. PAT estavel.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Deploys, sites e edge functions",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "huggingface",
        "display_name": "Hugging Face",
        "description": (
            "Servidor MCP remoto oficial em huggingface.co/mcp. Models, "
            "datasets, Spaces e inference. Auth via User Access Token."
        ),
        "transport_type": "http_sse",
        "transport_kind": "remote",
        "remote_url": "https://huggingface.co/mcp",
        "url": "https://huggingface.co/mcp",
        "env_schema": (_env_field("HF_TOKEN", "User Access Token", required=True),),
        "headers_schema": (),
        "documentation_url": "https://huggingface.co/docs/hub/mcp",
        "logo_key": "huggingface",
        "category": "data",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "official",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Servidor remoto oficial. Token via Authorization: Bearer.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Models, datasets, Spaces e inference",
            "manual_auth_header": {
                "header_name": "Authorization",
                "value_template": "Bearer {HF_TOKEN}",
            },
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
    {
        "server_key": "clickup",
        "display_name": "ClickUp",
        "description": (
            "Servidor MCP comunitario para ClickUp. Tasks, lists, folders, "
            "spaces, comments, time tracking. Auth via API Key + Team ID."
        ),
        "transport_type": "stdio",
        "transport_kind": "local",
        "command": ("npx", "-y", "clickup-mcp-server@1.12.0"),
        "env_schema": (
            _env_field("CLICKUP_API_KEY", "API Key", required=True),
            _env_field("CLICKUP_TEAM_ID", "Team ID", required=True, input_type="text"),
        ),
        "headers_schema": (),
        "documentation_url": "https://www.npmjs.com/package/clickup-mcp-server",
        "logo_key": "clickup",
        "category": "productivity",
        "enabled": True,
        "oauth_enabled": False,
        "auth_strategy": "api_token",
        "official_support_level": "community_manual",
        "oauth_mode": "none",
        "oauth_metadata_url": "",
        "tool_discovery_mode": "runtime",
        "vendor_notes": "Community/manual. API key + Team ID disponivel na URL do workspace.",
        "default_policy": "always_ask",
        "metadata": {
            "tagline": "Tasks, lists, spaces e time tracking",
            "auth_capabilities": {
                "oauth_enabled": False,
                "oauth_mode": "none",
                "supports_manual": True,
            },
        },
    },
)


def authoritative_mcp_catalog_entries() -> list[dict[str, Any]]:
    """Return authoritative MCP catalog entries as mutable payloads."""
    return [dict(entry) for entry in AUTHORITATIVE_MCP_CATALOG]
