"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition, type FormEvent } from "react";
import {
  CheckCircle2,
  CircleDashed,
  HardDriveDownload,
  KeyRound,
  LogIn,
  PlugZap,
  Rocket,
  ShieldAlert,
} from "lucide-react";
import { PageHeader } from "@/components/layout/header";
import {
  PageEmptyState,
  PageSection,
  PageSectionHeader,
  PageStatCard,
  PageStatGrid,
} from "@/components/ui/page-primitives";
import { requestJson } from "@/lib/http-client";
import type {
  ControlPlaneAuthStatus,
  ControlPlaneOnboardingStatus,
} from "@/lib/control-plane";

type BootstrapAuthMode = "api_key" | "local";

type SetupStep =
  | "setup_code"
  | "register_owner"
  | "login"
  | "finish_platform";

const SETUP_FLOW: ReadonlyArray<{
  step: SetupStep;
  label: string;
  helper: string;
}> = [
  {
    step: "setup_code",
    label: "Setup code",
    helper: "Pair this browser with the installer or CLI.",
  },
  {
    step: "register_owner",
    label: "Owner account",
    helper: "Create the first local operator.",
  },
  {
    step: "login",
    label: "Sign in",
    helper: "Open the HTTP-only operator session.",
  },
  {
    step: "finish_platform",
    label: "Finish setup",
    helper: "Configure access and the default provider.",
  },
] as const;

type BootstrapExchangeResponse = {
  ok: boolean;
  registration_token: string;
  expires_at?: string | null;
};

type DashboardAuthResponse = {
  ok: boolean;
  auth?: ControlPlaneAuthStatus | null;
  operator?: {
    username?: string | null;
    email?: string | null;
    display_name?: string | null;
  } | null;
};

const SUPPORTED_BOOTSTRAP_AUTH_MODES: BootstrapAuthMode[] = ["api_key", "local"];

function providerSupportsBootstrap(
  provider: ControlPlaneOnboardingStatus["providers"][number],
): boolean {
  return provider.supported_auth_modes.some((mode) =>
    SUPPORTED_BOOTSTRAP_AUTH_MODES.includes(mode as BootstrapAuthMode),
  );
}

function suggestedProviderId(status: ControlPlaneOnboardingStatus | null): string {
  if (!status) {
    return "";
  }
  if (status.system.default_provider) {
    return status.system.default_provider;
  }
  const verifiedProvider = status.providers.find((provider) => provider.verified);
  if (verifiedProvider) {
    return verifiedProvider.provider_id;
  }
  const configuredProvider = status.providers.find((provider) => provider.configured);
  if (configuredProvider) {
    return configuredProvider.provider_id;
  }
  const bootstrapProvider = status.providers.find(providerSupportsBootstrap);
  return bootstrapProvider?.provider_id ?? status.providers[0]?.provider_id ?? "";
}

function suggestedAuthMode(
  provider: ControlPlaneOnboardingStatus["providers"][number] | undefined,
): BootstrapAuthMode {
  const supported = (provider?.supported_auth_modes ?? []).filter((mode) =>
    SUPPORTED_BOOTSTRAP_AUTH_MODES.includes(mode as BootstrapAuthMode),
  ) as BootstrapAuthMode[];
  if (supported.includes("api_key")) {
    return "api_key";
  }
  if (supported.includes("local")) {
    return "local";
  }
  return "api_key";
}

function formatReadyState(ready: boolean) {
  return ready ? "Ready" : "Needs attention";
}

function formatAgentHint(status: ControlPlaneOnboardingStatus | null) {
  if (!status) {
    return "Optional during first run";
  }
  if (status.agents.length === 0) {
    return "Optional during first run";
  }
  const readyAgents = status.agents.filter((agent) => agent.telegram_token_configured).length;
  return `${readyAgents}/${status.agents.length} connected`;
}

function joinUserIds(status: ControlPlaneOnboardingStatus | null) {
  return status?.system.allowed_user_ids.join(", ") ?? "";
}

function defaultAgentName(status: ControlPlaneOnboardingStatus | null) {
  const ownerName = status?.system.owner_name?.trim();
  if (ownerName) {
    return `${ownerName}'s Agent`;
  }
  return "Koda Agent";
}

function deriveSetupStep({
  hasOperatorSession,
  hasOwner,
  registrationToken,
}: {
  hasOperatorSession: boolean;
  hasOwner: boolean;
  registrationToken: string;
}): SetupStep {
  if (hasOperatorSession) {
    return "finish_platform";
  }
  if (!hasOwner && registrationToken.trim()) {
    return "register_owner";
  }
  if (!hasOwner) {
    return "setup_code";
  }
  return "login";
}

function stepTitle(step: SetupStep) {
  switch (step) {
    case "setup_code":
      return "Connect with a setup code";
    case "register_owner":
      return "Create the owner account";
    case "login":
      return "Sign in to the control plane";
    case "finish_platform":
      return "Finish platform setup";
  }
}

function stepDescription(step: SetupStep) {
  switch (step) {
    case "setup_code":
      return "Paste the one-time setup code generated by the installer or CLI. It is short-lived and easier to rotate than exposing the raw recovery token.";
    case "register_owner":
      return "Create the local owner account that will drive dashboard sessions, API tokens, and future operator management.";
    case "login":
      return "Use the local owner account to open a secure HTTP-only operator session in the dashboard.";
    case "finish_platform":
      return "Storage is already online. Configure access policy, verify the default provider, and optionally connect the first agent.";
  }
}

function stepPosition(step: SetupStep) {
  return SETUP_FLOW.findIndex((item) => item.step === step);
}

function isStepComplete(
  step: SetupStep,
  {
    registrationToken,
    hasOwner,
    hasOperatorSession,
    onboardingComplete,
  }: {
    registrationToken: string;
    hasOwner: boolean;
    hasOperatorSession: boolean;
    onboardingComplete: boolean;
  },
) {
  switch (step) {
    case "setup_code":
      return Boolean(registrationToken.trim()) || hasOwner || hasOperatorSession;
    case "register_owner":
      return hasOwner || hasOperatorSession;
    case "login":
      return hasOperatorSession;
    case "finish_platform":
      return onboardingComplete;
  }
}

function formatDestination(nextTarget?: string | null) {
  return nextTarget || "/control-plane";
}

function guidanceForStep(step: SetupStep) {
  switch (step) {
    case "setup_code":
      return "Keep the terminal open after `koda install`. If the code expired, run `koda auth issue-code` and continue here.";
    case "register_owner":
      return "This is the long-lived dashboard identity. You can change the display name and email later in the control plane.";
    case "login":
      return "Use the username or email you just created. After sign-in, the dashboard stores the operator session in an HTTP-only cookie.";
    case "finish_platform":
      return "Access policy and provider are the only required inputs here. Creating the first Telegram agent is optional.";
  }
}

function StatusBadge({ ready }: { ready: boolean }) {
  return (
    <span
      className={[
        "inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em]",
        ready
          ? "border-emerald-400/40 bg-emerald-400/10 text-emerald-200"
          : "border-amber-400/40 bg-amber-400/10 text-amber-100",
      ].join(" ")}
    >
      {ready ? <CheckCircle2 className="h-3.5 w-3.5" /> : <CircleDashed className="h-3.5 w-3.5" />}
      {formatReadyState(ready)}
    </span>
  );
}

function RecoveryTokenPanel({
  enabled,
  pendingAction,
  onSubmit,
}: {
  enabled: boolean;
  pendingAction: string | null;
  onSubmit: (token: string) => Promise<void>;
}) {
  const [token, setToken] = useState("");
  const [error, setError] = useState<string | null>(null);

  if (!enabled) {
    return null;
  }

  return (
    <details className="rounded-3xl border border-[var(--border-subtle)] bg-background/40 p-4">
      <summary className="cursor-pointer list-none text-sm font-medium text-[var(--text-primary)]">
        Use the recovery token instead
      </summary>
      <p className="mt-3 text-sm text-[var(--text-secondary)]">
        Compatibility is still available for one migration cycle, but the recommended path is
        setup code plus owner account.
      </p>
      <form
        className="mt-4 space-y-3"
        onSubmit={async (event) => {
          event.preventDefault();
          setError(null);
          const trimmed = token.trim();
          if (!trimmed) {
            setError("Recovery token is required.");
            return;
          }
          try {
            await onSubmit(trimmed);
            setToken("");
          } catch (submitError) {
            setError(
              submitError instanceof Error
                ? submitError.message
                : "Could not validate the recovery token.",
            );
          }
        }}
      >
        <label className="grid gap-2 text-sm">
          Recovery token
          <input
            className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
            value={token}
            onChange={(event) => setToken(event.target.value)}
            placeholder="CONTROL_PLANE_API_TOKEN"
            type="password"
            autoComplete="off"
            spellCheck={false}
          />
        </label>
        {error ? <p className="text-sm text-[var(--tone-danger-text)]">{error}</p> : null}
        <button
          className="button-shell button-shell--secondary button-shell--sm"
          disabled={pendingAction === "recovery"}
          type="submit"
        >
          {pendingAction === "recovery" ? "Opening session..." : "Use recovery token"}
        </button>
      </form>
    </details>
  );
}

export function ControlPlaneSetup({
  initialStatus,
  authStatus,
  initialRegistrationToken = "",
  initialRegistrationExpiresAt = null,
  nextTarget = null,
}: {
  initialStatus?: ControlPlaneOnboardingStatus | null;
  authStatus?: ControlPlaneAuthStatus | null;
  initialRegistrationToken?: string;
  initialRegistrationExpiresAt?: string | null;
  nextTarget?: string | null;
}) {
  const router = useRouter();
  const [isRefreshing, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [pendingAction, setPendingAction] = useState<
    "exchange" | "register" | "login" | "logout" | "bootstrap" | "recovery" | null
  >(null);

  const [setupCode, setSetupCode] = useState("");
  const [registrationToken, setRegistrationToken] = useState(initialRegistrationToken);
  const [registrationExpiresAt, setRegistrationExpiresAt] = useState<string | null>(
    initialRegistrationExpiresAt,
  );
  const [username, setUsername] = useState("");
  const [displayName, setDisplayName] = useState(initialStatus?.system.owner_name ?? "");
  const [email, setEmail] = useState(initialStatus?.system.owner_email ?? "");
  const [password, setPassword] = useState("");
  const [identifier, setIdentifier] = useState("");

  const [createAgentNow, setCreateAgentNow] = useState(false);
  const [ownerName, setOwnerName] = useState(initialStatus?.system.owner_name ?? "");
  const [ownerEmail, setOwnerEmail] = useState(initialStatus?.system.owner_email ?? "");
  const [ownerGithub, setOwnerGithub] = useState(initialStatus?.system.owner_github ?? "");
  const [allowedUserIds, setAllowedUserIds] = useState(joinUserIds(initialStatus ?? null));
  const [providerId, setProviderId] = useState(suggestedProviderId(initialStatus ?? null));
  const bootstrapProviders = (initialStatus?.providers ?? []).filter(providerSupportsBootstrap);
  const selectedProvider =
    bootstrapProviders.find((provider) => provider.provider_id === providerId) ?? bootstrapProviders[0];
  const [authMode, setAuthMode] = useState<BootstrapAuthMode>(suggestedAuthMode(selectedProvider));
  const [apiKey, setApiKey] = useState("");
  const [projectId, setProjectId] = useState("");
  const [baseUrl, setBaseUrl] = useState("");
  const [agentId, setAgentId] = useState("AGENT_A");
  const [agentDisplayName, setAgentDisplayName] = useState(defaultAgentName(initialStatus ?? null));
  const [agentTelegramToken, setAgentTelegramToken] = useState("");

  const hasOperatorSession = Boolean(authStatus?.authenticated);
  const hasOwner = Boolean(authStatus?.has_owner ?? initialStatus?.has_owner);
  const currentStep = deriveSetupStep({
    hasOperatorSession,
    hasOwner,
    registrationToken,
  });
  const currentStepPosition = stepPosition(currentStep);
  const operatorLabel =
    authStatus?.operator?.display_name ||
    authStatus?.operator?.username ||
    "Operator";
  const onboardingComplete = Boolean(initialStatus?.steps.onboarding_complete);
  const destinationAfterSetup = formatDestination(nextTarget);

  const storageReady = Boolean(
    initialStatus?.storage.database.ready && initialStatus?.storage.object_storage.ready,
  );
  const providerConfigured = Boolean(initialStatus?.steps.provider_configured);
  const providerRequiresApiKey =
    authMode === "api_key" &&
    !selectedProvider?.configured &&
    !selectedProvider?.verified &&
    !apiKey.trim();
  const canSubmitBootstrap =
    hasOperatorSession &&
    storageReady &&
    Boolean(providerId.trim()) &&
    Boolean(allowedUserIds.trim()) &&
    !providerRequiresApiKey;

  function refreshRoute() {
    startTransition(() => {
      router.refresh();
    });
  }

  async function submitRecoveryToken(token: string) {
    setError(null);
    setSuccess(null);
    setPendingAction("recovery");
    try {
      await requestJson("/api/control-plane/web-auth", {
        method: "POST",
        body: JSON.stringify({ token }),
      });
      setSuccess("Recovery session opened. Redirecting to the dashboard setup...");
      refreshRoute();
    } finally {
      setPendingAction(null);
    }
  }

  async function submitSetupCode(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError(null);
    setSuccess(null);
    const trimmedCode = setupCode.trim();
    if (!trimmedCode) {
      setError("Setup code is required.");
      return;
    }
    setPendingAction("exchange");
    try {
      const payload = await requestJson<BootstrapExchangeResponse>(
        "/api/control-plane/auth/bootstrap/exchange",
        {
          method: "POST",
          body: JSON.stringify({ code: trimmedCode }),
        },
      );
      setRegistrationToken(payload.registration_token);
      setRegistrationExpiresAt(payload.expires_at ?? null);
      setSetupCode("");
      setSuccess("Setup code accepted. Create the owner account to continue.");
    } catch (submitError) {
      setError(
        submitError instanceof Error
          ? submitError.message
          : "Could not exchange the setup code.",
      );
    } finally {
      setPendingAction(null);
    }
  }

  async function submitOwnerRegistration(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError(null);
    setSuccess(null);
    if (!registrationToken.trim()) {
      setError("Exchange a setup code before creating the owner account.");
      return;
    }
    setPendingAction("register");
    try {
      const payload = await requestJson<DashboardAuthResponse>(
        "/api/control-plane/auth/register-owner",
        {
          method: "POST",
          body: JSON.stringify({
            registration_token: registrationToken,
            username,
            email,
            password,
            display_name: displayName,
          }),
        },
      );
      setSuccess(
        payload.operator?.display_name
          ? `Owner account created for ${payload.operator.display_name}.`
          : "Owner account created. Loading the dashboard...",
      );
      setRegistrationToken("");
      setPassword("");
      refreshRoute();
    } catch (submitError) {
      setError(
        submitError instanceof Error
          ? submitError.message
          : "Could not create the owner account.",
      );
    } finally {
      setPendingAction(null);
    }
  }

  async function submitLogin(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError(null);
    setSuccess(null);
    if (!identifier.trim() || !password) {
      setError("Identifier and password are required.");
      return;
    }
    setPendingAction("login");
    try {
      const payload = await requestJson<DashboardAuthResponse>("/api/control-plane/auth/login", {
        method: "POST",
        body: JSON.stringify({
          identifier,
          password,
        }),
      });
      setPassword("");
      setSuccess(
        payload.auth?.operator?.display_name
          ? `Welcome back, ${payload.auth.operator.display_name}.`
          : "Signed in. Loading the control plane...",
      );
      refreshRoute();
    } catch (submitError) {
      setError(
        submitError instanceof Error
          ? submitError.message
          : "Could not sign in to the control plane.",
      );
    } finally {
      setPendingAction(null);
    }
  }

  async function disconnectOperatorSession() {
    setError(null);
    setSuccess(null);
    setPendingAction("logout");
    try {
      await requestJson("/api/control-plane/auth/logout", {
        method: "POST",
      });
      setSuccess("Operator session cleared.");
      refreshRoute();
    } catch (submitError) {
      setError(
        submitError instanceof Error
          ? submitError.message
          : "Could not clear the operator session.",
      );
    } finally {
      setPendingAction(null);
    }
  }

  async function submitBootstrap(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError(null);
    setSuccess(null);

    if (!canSubmitBootstrap) {
      setError("Finish storage, access, and provider details before continuing.");
      return;
    }

    setPendingAction("bootstrap");
    try {
      const payload = await requestJson<{ ok: boolean; status: ControlPlaneOnboardingStatus }>(
        "/api/control-plane/onboarding/bootstrap",
        {
          method: "POST",
          body: JSON.stringify({
            account: {
              owner_name: ownerName.trim(),
              owner_email: ownerEmail.trim(),
              owner_github: ownerGithub.trim(),
            },
            access: {
              allowed_user_ids: allowedUserIds,
            },
            provider: {
              provider_id: providerId,
              auth_mode: authMode,
              api_key: apiKey.trim(),
              project_id: projectId.trim(),
              base_url: baseUrl.trim(),
            },
            agent: createAgentNow
              ? {
                  agent_id: agentId.trim(),
                  display_name: agentDisplayName.trim(),
                  telegram_token: agentTelegramToken.trim(),
                }
              : {},
          }),
        },
      );

      setSuccess(
        payload.status.steps.onboarding_complete
          ? "Initial configuration saved. Opening the control plane..."
          : "Configuration saved. You can continue refining settings in the control plane.",
      );
      refreshRoute();
    } catch (submitError) {
      setError(
        submitError instanceof Error
          ? submitError.message
          : "Could not apply the initial configuration.",
      );
    } finally {
      setPendingAction(null);
    }
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title={stepTitle(currentStep)}
        description={`${stepDescription(currentStep)} ${nextTarget ? `After setup, Koda will continue to ${destinationAfterSetup}.` : "When setup is complete, Koda opens the control-plane home automatically."}`}
      />

      <PageSection className="space-y-5 p-5 sm:p-6">
        <PageSectionHeader
          eyebrow="Quickstart"
          title="Guided first-run setup"
          description="Start with the setup code, create the owner account, sign in, and then finish the minimum platform bootstrap. `/control-plane` unlocks after these checkpoints are ready."
          actions={
            hasOperatorSession ? (
              <button
                type="button"
                className="button-shell button-shell--secondary button-shell--sm"
                onClick={() => void disconnectOperatorSession()}
                disabled={pendingAction === "logout" || isRefreshing}
              >
                {pendingAction === "logout" ? "Signing out..." : "Sign out"}
              </button>
            ) : undefined
          }
        />

        <div className="grid gap-3 lg:grid-cols-4">
          {SETUP_FLOW.map(({ step, label, helper }, index) => {
            const complete = isStepComplete(step, {
              registrationToken,
              hasOwner,
              hasOperatorSession,
              onboardingComplete,
            });
            const active = step === currentStep;
            return (
              <div
                key={step}
                className={[
                  "rounded-[24px] border px-4 py-4 transition-colors",
                  active
                    ? "border-[var(--border-strong)] bg-[var(--surface-panel-soft)]"
                    : complete
                      ? "border-emerald-400/30 bg-emerald-400/10"
                      : "border-[var(--border-subtle)] bg-background/40",
                ].join(" ")}
              >
                <div className="flex items-center gap-3">
                  <span
                    className={[
                      "flex h-9 w-9 shrink-0 items-center justify-center rounded-2xl border text-xs font-semibold uppercase tracking-[0.16em]",
                      active
                        ? "border-[var(--border-strong)] bg-background text-[var(--text-primary)]"
                        : complete
                          ? "border-emerald-400/40 bg-background text-emerald-200"
                          : "border-[var(--border-subtle)] bg-background text-[var(--text-secondary)]",
                    ].join(" ")}
                  >
                    {complete ? <CheckCircle2 className="h-4 w-4" /> : index + 1}
                  </span>
                  <div className="min-w-0">
                    <p className="text-sm font-semibold text-[var(--text-primary)]">{label}</p>
                    <p className="text-xs leading-5 text-[var(--text-secondary)]">{helper}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        <PageStatGrid className="grid-cols-1 xl:grid-cols-4">
          <PageStatCard
            label="Owner account"
            value={hasOwner ? "Ready" : registrationToken ? "Pending" : "Needs setup"}
            hint={
              hasOwner
                ? authStatus?.operator?.email || "Local account configured"
                : registrationToken
                  ? "Registration token issued"
                  : "No local owner account yet"
            }
            className={!hasOwner ? "border-amber-400/30" : undefined}
          />
          <PageStatCard
            label="Operator session"
            value={hasOperatorSession ? "Ready" : "Required"}
            hint={hasOperatorSession ? operatorLabel : "Sign in required for control-plane changes"}
            className={!hasOperatorSession ? "border-amber-400/30" : undefined}
          />
          <PageStatCard
            label="Default provider"
            value={formatReadyState(providerConfigured)}
            hint={selectedProvider?.title ?? "Choose a verified provider"}
            className={hasOperatorSession && !providerConfigured ? "border-amber-400/30" : undefined}
          />
          <PageStatCard
            label="First agent"
            value={formatAgentHint(initialStatus ?? null)}
            hint="Optional during first run"
          />
        </PageStatGrid>

        <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_340px]">
          <div className="rounded-[24px] border border-[var(--border-subtle)] bg-background/40 px-4 py-4">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--text-secondary)]">
              What you need now
            </p>
            <p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">
              {guidanceForStep(currentStep)}
            </p>
          </div>
          <div className="rounded-[24px] border border-[var(--border-subtle)] bg-background/40 px-4 py-4">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--text-secondary)]">
              Destination after setup
            </p>
            <p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">
              {nextTarget
                ? `Koda will return you to ${destinationAfterSetup} after auth and bootstrap are complete.`
                : "Koda will open /control-plane after auth and bootstrap are complete."}
            </p>
          </div>
        </div>

        <div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_360px]">
          {currentStep === "setup_code" ? (
            <div className="space-y-4 rounded-[28px] border border-[var(--border-subtle)] bg-[var(--surface-panel-soft)] p-5">
              <form className="space-y-4" onSubmit={submitSetupCode}>
                <div className="space-y-2">
                  <div className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--text-secondary)]">
                    <KeyRound className="h-4 w-4" />
                    Pairing flow
                  </div>
                  <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                    Exchange the setup code
                  </h2>
                  <p className="text-sm text-[var(--text-secondary)]">
                    Local installs can open the dashboard and print this code automatically. For
                    headless or VPS environments, the installer should output the same code plus its
                    expiry.
                  </p>
                </div>

                <div className="grid gap-3 md:grid-cols-3">
                  <div className="rounded-2xl border border-[var(--border-subtle)] bg-background/70 px-3 py-3">
                    <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--text-secondary)]">
                      Local install
                    </p>
                    <code className="mt-2 block text-sm text-[var(--text-primary)]">koda install</code>
                  </div>
                  <div className="rounded-2xl border border-[var(--border-subtle)] bg-background/70 px-3 py-3">
                    <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--text-secondary)]">
                      VPS or headless
                    </p>
                    <code className="mt-2 block text-sm text-[var(--text-primary)]">
                      koda install --headless
                    </code>
                  </div>
                  <div className="rounded-2xl border border-[var(--border-subtle)] bg-background/70 px-3 py-3">
                    <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--text-secondary)]">
                      Need a new code?
                    </p>
                    <code className="mt-2 block text-sm text-[var(--text-primary)]">
                      koda auth issue-code
                    </code>
                  </div>
                </div>

                <label className="grid gap-2 text-sm">
                  Setup code
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={setupCode}
                    onChange={(event) => setSetupCode(event.target.value.toUpperCase())}
                    placeholder="ABCD-EFGH-JKLM"
                    autoComplete="one-time-code"
                    spellCheck={false}
                  />
                </label>

                {error ? <p className="text-sm text-[var(--tone-danger-text)]">{error}</p> : null}
                {success ? <p className="text-sm text-[var(--tone-success-dot)]">{success}</p> : null}

                <div className="flex flex-wrap items-center gap-3">
                  <button
                    className="button-shell button-shell--primary"
                    disabled={pendingAction === "exchange" || isRefreshing}
                    type="submit"
                  >
                    {pendingAction === "exchange" ? "Exchanging..." : "Continue with setup code"}
                  </button>
                  <button
                    type="button"
                    className="button-shell button-shell--secondary button-shell--sm"
                    onClick={() => refreshRoute()}
                    disabled={isRefreshing}
                  >
                    Refresh status
                  </button>
                </div>
              </form>

              <RecoveryTokenPanel
                enabled={Boolean(authStatus?.recovery_available)}
                pendingAction={pendingAction}
                onSubmit={submitRecoveryToken}
              />
            </div>
          ) : null}

          {currentStep === "register_owner" ? (
            <form
              className="space-y-5 rounded-[28px] border border-[var(--border-subtle)] bg-[var(--surface-panel-soft)] p-5"
              onSubmit={submitOwnerRegistration}
            >
              <div className="space-y-2">
                <div className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--text-secondary)]">
                  <Rocket className="h-4 w-4" />
                  Owner bootstrap
                </div>
                <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                  Create the local owner account
                </h2>
                <p className="text-sm text-[var(--text-secondary)]">
                  This account replaces the old browser token flow. Sessions stay in secure cookies
                  and API/CLI access can be managed separately afterwards.
                </p>
                {registrationExpiresAt ? (
                  <p className="text-xs text-[var(--text-secondary)]">
                    Registration token expires at {registrationExpiresAt}
                  </p>
                ) : null}
              </div>

              <section className="grid gap-4 md:grid-cols-2">
                <label className="grid gap-2 text-sm md:col-span-2">
                  Display name
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={displayName}
                    onChange={(event) => setDisplayName(event.target.value)}
                    placeholder="Koda Owner"
                  />
                </label>
                <label className="grid gap-2 text-sm">
                  Username
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={username}
                    onChange={(event) => setUsername(event.target.value)}
                    placeholder="koda-owner"
                    autoComplete="username"
                  />
                </label>
                <label className="grid gap-2 text-sm">
                  Email
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={email}
                    onChange={(event) => setEmail(event.target.value)}
                    placeholder="owner@example.com"
                    type="email"
                    autoComplete="email"
                  />
                </label>
                <label className="grid gap-2 text-sm md:col-span-2">
                  Password
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={password}
                    onChange={(event) => setPassword(event.target.value)}
                    placeholder="Use at least 8 characters"
                    type="password"
                    autoComplete="new-password"
                  />
                </label>
              </section>

              {error ? <p className="text-sm text-[var(--tone-danger-text)]">{error}</p> : null}
              {success ? <p className="text-sm text-[var(--tone-success-dot)]">{success}</p> : null}

              <div className="flex flex-wrap items-center gap-3">
                <button
                  className="button-shell button-shell--primary"
                  disabled={pendingAction === "register" || isRefreshing}
                  type="submit"
                >
                  {pendingAction === "register" ? "Creating account..." : "Create owner account"}
                </button>
                <button
                  type="button"
                  className="button-shell button-shell--secondary button-shell--sm"
                  onClick={() => {
                    setRegistrationToken("");
                    setRegistrationExpiresAt(null);
                    setError(null);
                    setSuccess(null);
                  }}
                >
                  Use a different setup code
                </button>
              </div>
            </form>
          ) : null}

          {currentStep === "login" ? (
            <div className="space-y-4 rounded-[28px] border border-[var(--border-subtle)] bg-[var(--surface-panel-soft)] p-5">
              <form className="space-y-4" onSubmit={submitLogin}>
                <div className="space-y-2">
                  <div className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--text-secondary)]">
                    <LogIn className="h-4 w-4" />
                    Local account
                  </div>
                  <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                    Sign in with the owner account
                  </h2>
                  <p className="text-sm text-[var(--text-secondary)]">
                    The browser session is stored in an HTTP-only cookie. Raw tokens are no longer
                    required for everyday operator access.
                  </p>
                </div>

                <label className="grid gap-2 text-sm">
                  Username or email
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={identifier}
                    onChange={(event) => setIdentifier(event.target.value)}
                    placeholder="owner@example.com"
                    autoComplete="username"
                  />
                </label>
                <label className="grid gap-2 text-sm">
                  Password
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={password}
                    onChange={(event) => setPassword(event.target.value)}
                    placeholder="Enter the owner password"
                    type="password"
                    autoComplete="current-password"
                  />
                </label>

                {error ? <p className="text-sm text-[var(--tone-danger-text)]">{error}</p> : null}
                {success ? <p className="text-sm text-[var(--tone-success-dot)]">{success}</p> : null}

                <button
                  className="button-shell button-shell--primary"
                  disabled={pendingAction === "login" || isRefreshing}
                  type="submit"
                >
                  {pendingAction === "login" ? "Signing in..." : "Sign in"}
                </button>
              </form>

              <RecoveryTokenPanel
                enabled={Boolean(authStatus?.recovery_available)}
                pendingAction={pendingAction}
                onSubmit={submitRecoveryToken}
              />
            </div>
          ) : null}

          {currentStep === "finish_platform" ? (
            <form
              className="space-y-6 rounded-[28px] border border-[var(--border-subtle)] bg-[var(--surface-panel-soft)] p-5"
              onSubmit={submitBootstrap}
            >
              <div className="space-y-2">
                <div className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--text-secondary)]">
                  <Rocket className="h-4 w-4" />
                  Initial configuration
                </div>
                <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                  Configure access and the default provider
                </h2>
                <p className="text-sm text-[var(--text-secondary)]">
                  The goal is to get the product usable quickly. Provider setup and access are
                  required; creating the first Telegram agent is optional and can happen right
                  after this screen.
                </p>
              </div>

              <section className="grid gap-4 md:grid-cols-2">
                <label className="grid gap-2 text-sm">
                  Owner name
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={ownerName}
                    onChange={(event) => setOwnerName(event.target.value)}
                    placeholder="Open Source Maintainer"
                  />
                </label>
                <label className="grid gap-2 text-sm">
                  Owner email
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={ownerEmail}
                    onChange={(event) => setOwnerEmail(event.target.value)}
                    placeholder="maintainer@example.com"
                    type="email"
                  />
                </label>
                <label className="grid gap-2 text-sm md:col-span-2">
                  Owner GitHub
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={ownerGithub}
                    onChange={(event) => setOwnerGithub(event.target.value)}
                    placeholder="openkodaai"
                  />
                </label>
              </section>

              <section className="space-y-3">
                <div className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--text-secondary)]">
                  <PlugZap className="h-4 w-4" />
                  Access policy
                </div>
                <label className="grid gap-2 text-sm">
                  Allowed Telegram user IDs
                  <input
                    className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                    value={allowedUserIds}
                    onChange={(event) => setAllowedUserIds(event.target.value)}
                    placeholder="123456789,987654321"
                    required
                  />
                </label>
                <p className="text-xs text-[var(--text-secondary)]">
                  These IDs become the initial allowed operators and knowledge admins. You can
                  refine the policy later in system settings.
                </p>
              </section>

              <section className="space-y-4">
                <div className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--text-secondary)]">
                  <HardDriveDownload className="h-4 w-4" />
                  Default provider
                </div>
                <div className="grid gap-4 md:grid-cols-2">
                  <label className="grid gap-2 text-sm">
                    Provider
                    <select
                      className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                      value={providerId}
                      onChange={(event) => {
                        const nextProviderId = event.target.value;
                        const nextProvider = bootstrapProviders.find(
                          (provider) => provider.provider_id === nextProviderId,
                        );
                        setProviderId(nextProviderId);
                        setAuthMode(suggestedAuthMode(nextProvider));
                      }}
                    >
                      {bootstrapProviders.map((provider) => (
                        <option key={provider.provider_id} value={provider.provider_id}>
                          {provider.title}
                        </option>
                      ))}
                    </select>
                  </label>
                  <label className="grid gap-2 text-sm">
                    Auth mode
                    <select
                      className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                      value={authMode}
                      onChange={(event) => setAuthMode(event.target.value as BootstrapAuthMode)}
                    >
                      {(
                        selectedProvider?.supported_auth_modes.filter((mode) =>
                          SUPPORTED_BOOTSTRAP_AUTH_MODES.includes(mode as BootstrapAuthMode),
                        ) ?? [authMode]
                      ).map((mode) => (
                        <option key={mode} value={mode}>
                          {mode === "api_key" ? "API key" : "Local / server"}
                        </option>
                      ))}
                    </select>
                  </label>
                  {authMode === "api_key" ? (
                    <>
                      <label className="grid gap-2 text-sm">
                        API key
                        <input
                          className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                          value={apiKey}
                          onChange={(event) => setApiKey(event.target.value)}
                          placeholder={
                            selectedProvider?.configured || selectedProvider?.verified
                              ? "Leave blank to keep the existing credential"
                              : "Paste the provider API key"
                          }
                          type="password"
                          autoComplete="off"
                        />
                      </label>
                      <label className="grid gap-2 text-sm">
                        Project ID
                        <input
                          className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                          value={projectId}
                          onChange={(event) => setProjectId(event.target.value)}
                          placeholder="Only needed for providers that require a project"
                        />
                      </label>
                    </>
                  ) : null}
                  <label className="grid gap-2 text-sm md:col-span-2">
                    Base URL
                    <input
                      className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                      value={baseUrl}
                      onChange={(event) => setBaseUrl(event.target.value)}
                      placeholder={
                        authMode === "local"
                          ? "http://host.docker.internal:11434"
                          : "Optional custom endpoint"
                      }
                    />
                  </label>
                </div>
                {providerRequiresApiKey ? (
                  <p className="text-sm text-amber-200">
                    This provider needs an API key before the first verification can run.
                  </p>
                ) : null}
              </section>

              <section className="space-y-4 rounded-3xl border border-[var(--border-subtle)] bg-[var(--surface-panel-soft)] p-4">
                <label className="flex items-start gap-3 text-sm">
                  <input
                    type="checkbox"
                    className="mt-1 h-4 w-4"
                    checked={createAgentNow}
                    onChange={(event) => setCreateAgentNow(event.target.checked)}
                  />
                  <span className="space-y-1">
                    <span className="block font-medium text-[var(--text-primary)]">
                      Connect the first Telegram agent now
                    </span>
                    <span className="block text-[var(--text-secondary)]">
                      Optional. You can also finish setup first and create agents from the control
                      plane catalog right after.
                    </span>
                  </span>
                </label>

                {createAgentNow ? (
                  <div className="grid gap-4 md:grid-cols-2">
                    <label className="grid gap-2 text-sm">
                      Agent ID
                      <input
                        className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                        value={agentId}
                        onChange={(event) => setAgentId(event.target.value.toUpperCase())}
                        placeholder="AGENT_A"
                      />
                    </label>
                    <label className="grid gap-2 text-sm">
                      Display name
                      <input
                        className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                        value={agentDisplayName}
                        onChange={(event) => setAgentDisplayName(event.target.value)}
                        placeholder="Koda Agent"
                      />
                    </label>
                    <label className="grid gap-2 text-sm md:col-span-2">
                      Telegram token
                      <input
                        className="rounded-2xl border border-[var(--border-subtle)] bg-background px-4 py-3 text-[var(--text-primary)] outline-none focus-visible:border-[var(--border-strong)]"
                        value={agentTelegramToken}
                        onChange={(event) => setAgentTelegramToken(event.target.value)}
                        placeholder="Paste the bot token from BotFather"
                        type="password"
                        autoComplete="off"
                      />
                    </label>
                  </div>
                ) : null}
              </section>

              {error ? <p className="text-sm text-[var(--tone-danger-text)]">{error}</p> : null}
              {success ? <p className="text-sm text-[var(--tone-success-dot)]">{success}</p> : null}

              <div className="flex flex-wrap items-center gap-3">
                <button
                  type="submit"
                  className="button-shell button-shell--primary"
                  disabled={!canSubmitBootstrap || pendingAction === "bootstrap" || isRefreshing}
                >
                  {pendingAction === "bootstrap"
                    ? "Saving setup..."
                    : "Apply setup and open the control plane"}
                </button>
                <button
                  type="button"
                  className="button-shell button-shell--secondary button-shell--sm"
                  onClick={() => refreshRoute()}
                  disabled={isRefreshing}
                >
                  Refresh status
                </button>
              </div>
            </form>
          ) : null}

          <aside className="space-y-4 rounded-[28px] border border-[var(--border-subtle)] bg-[var(--surface-panel-soft)] p-5">
            <div className="space-y-2">
              <h2 className="text-sm font-semibold uppercase tracking-[0.2em] text-[var(--text-secondary)]">
                Current checkpoint
              </h2>
              <p className="text-sm text-[var(--text-secondary)]">
                Step {currentStepPosition + 1} of {SETUP_FLOW.length}. This panel follows the
                first-run path as auth and platform bootstrap become ready.
              </p>
            </div>

            <div className="rounded-2xl border border-[var(--border-subtle)] px-4 py-3">
              <p className="text-sm font-medium text-[var(--text-primary)]">Current step</p>
              <p className="mt-1 text-xs text-[var(--text-secondary)]">{stepTitle(currentStep)}</p>
            </div>

            <div className="rounded-2xl border border-[var(--border-subtle)] px-4 py-3">
              <p className="text-sm font-medium text-[var(--text-primary)]">What happens next</p>
              <p className="mt-1 text-xs text-[var(--text-secondary)]">
                {nextTarget
                  ? `Once setup is complete, Koda will continue to ${destinationAfterSetup}.`
                  : "Once setup is complete, Koda will open the control-plane home and agent catalog."}
              </p>
            </div>

            <div className="rounded-2xl border border-[var(--border-subtle)] px-4 py-3">
              <p className="text-sm font-medium text-[var(--text-primary)]">Authentication mode</p>
              <p className="mt-1 text-xs text-[var(--text-secondary)]">
                {authStatus?.auth_mode || initialStatus?.auth_mode || "local_account"}
              </p>
            </div>

            <div className="rounded-2xl border border-[var(--border-subtle)] px-4 py-3">
              <p className="text-sm font-medium text-[var(--text-primary)]">Migration compatibility</p>
              <p className="mt-1 text-xs text-[var(--text-secondary)]">
                {authStatus?.recovery_available
                  ? "Recovery token exchange is still available, but the preferred path is setup code plus owner login."
                  : "No legacy recovery token exposed in the UI."}
              </p>
            </div>

            {initialStatus ? (
              <div className="space-y-3">
                <div className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--border-subtle)] px-4 py-3">
                  <div>
                    <p className="text-sm font-medium text-[var(--text-primary)]">Database</p>
                    <p className="text-xs text-[var(--text-secondary)]">
                      {initialStatus.storage.database.reason || "Postgres and schema bootstrap"}
                    </p>
                  </div>
                  <StatusBadge ready={Boolean(initialStatus.storage.database.ready)} />
                </div>

                <div className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--border-subtle)] px-4 py-3">
                  <div>
                    <p className="text-sm font-medium text-[var(--text-primary)]">Object storage</p>
                    <p className="text-xs text-[var(--text-secondary)]">
                      {initialStatus.storage.object_storage.reason || "Bundled S3-compatible storage"}
                    </p>
                  </div>
                  <StatusBadge ready={Boolean(initialStatus.storage.object_storage.ready)} />
                </div>

                <div className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--border-subtle)] px-4 py-3">
                  <div>
                    <p className="text-sm font-medium text-[var(--text-primary)]">Access policy</p>
                    <p className="text-xs text-[var(--text-secondary)]">
                      {joinUserIds(initialStatus) || "No Telegram user IDs configured yet"}
                    </p>
                  </div>
                  <StatusBadge ready={Boolean(initialStatus.steps.access_configured)} />
                </div>

                <div className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--border-subtle)] px-4 py-3">
                  <div>
                    <p className="text-sm font-medium text-[var(--text-primary)]">Provider</p>
                    <p className="text-xs text-[var(--text-secondary)]">
                      {selectedProvider?.title || "Choose the first verified provider"}
                    </p>
                  </div>
                  <StatusBadge ready={Boolean(initialStatus.steps.provider_configured)} />
                </div>
              </div>
            ) : (
              <PageEmptyState
                title="Setup status loads after bootstrap"
                description="Once the control plane exposes onboarding status, this panel shows storage, provider, and access checkpoints."
              />
            )}

            {!hasOwner ? (
              <div className="rounded-3xl border border-amber-400/30 bg-amber-400/10 p-4">
                <div className="flex items-start gap-3">
                  <ShieldAlert className="mt-0.5 h-4 w-4 text-amber-200" />
                  <div className="space-y-1">
                    <p className="text-sm font-medium text-amber-100">Secure bootstrap</p>
                    <p className="text-xs text-amber-50/90">
                      Setup codes are one-time and short-lived. The recovery token remains
                      break-glass only and should not be the everyday login path anymore.
                    </p>
                  </div>
                </div>
              </div>
            ) : null}
          </aside>
        </div>
      </PageSection>
    </div>
  );
}
